'use client';
import SiteHeader from '../SiteHeader';
import {useState} from 'react';
const OneMark=()=> <span className="oneMark"><b>1</b><i>%</i></span>;
const stages=[
 ['01','1% 企業夥伴','完成企業身份與第一筆真實共享紀錄'],
 ['02','持續共享夥伴','持續參與，不只一次性合作'],
 ['03','資源連結夥伴','開始提供工作、專業、服務或 人脈連結'],
 ['04','影響力夥伴','共享跨越 公益關懷 × 資源連結，形成可追蹤影響'],
 ['05','善循環夥伴','長期穩定參與，並促成新的 1% 回到網絡']
];
export default function Partner(){const [stage,setStage]=useState(2);return <main className="partnerPage">
<SiteHeader/>
<section className="partnerHero esgHero"><div className="portalWrap"><div><div className="eyebrow">1% PARTNER · 企業 ESG 服務</div><h1>讓企業的 1%，成為看得見的 影響力成果。</h1><p>從公益行動、員工參與、專業與資源共享，到 ESG 專案執行與成果整理，RCSCA 讓企業找到適合自己的參與方式。</p><div className="heroActions"><a className="primary light" href="#esg-services">探索 ESG 合作方案</a><a className="outlineLight" href="/1percent-partner/dashboard">企業管理入口</a><a className="outlineLight" href="/1percent-partner/apply">成為 1% PARTNER</a></div></div><div className={`enterpriseCard stage-${stage}`}><small>RCSCA · 1% PARTNER</small><strong>ACME COMPANY</strong><span>共享階段 {stage} · {stages[stage-1][1]}</span><em>2027 企業夥伴</em><OneMark/></div></div></section>
<section id="esg-services" className="portalSection esgServices"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">企業 ESG 服務</div><h2>把企業想做的事，轉成真正能落地的影響。</h2></div><p>公益不是曝光商品。企業委託的是企劃、執行、人力、影像與成果整理等專業服務；公益資源仍依真實需求流動。</p></div><div className="portalGrid four"><article><small>社會影響力專案</small><h3>社會影響力專案</h3><p>從需求盤點、企劃、媒合到執行，建立可落地的公益與社會影響力專案。</p></article><article><small>員工參與</small><h3>員工參與</h3><p>企業志工、員工與家庭參與，讓 ESG 不只停留在報告裡。</p></article><article><small>資源媒合</small><h3>資源媒合</h3><p>讓產品、專業、服務、場地與工作機會進到真正需要的位置。</p></article><article><small>成果與永續素材</small><h3>成果與素材</h3><p>整理年度 影響力成果、成果紀錄與可供永續報告使用的真實素材。</p></article></div><a className="esgLead" href="/1percent-partner/esg">提出企業合作需求 →</a><a className="subtleInlineLink" href="/1percent-partner/collaboration">查看企業合作流程 →</a><a className="subtleInlineLink" href="/1percent-partner/cases">查看合作案例模型 →</a></div></section>
<section id="partner-journey" className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">企業共享旅程</div><h2>不是誰贊助最多，而是共享走得多深。</h2></div><p>企業成長階段依持續參與、實際共享、工作機會、專業服務、人脈連結 與 影響力成果 綜合形成；不以金額買等級。</p></div><div className="partnerStages">{stages.map((s,i)=><button key={s[0]} className={stage===i+1?'active':''} onClick={()=>setStage(i+1)}><small>{s[0]}</small><b>{s[1]}</b><span>{s[2]}</span></button>)}</div></div></section>
<section className="portalSection darkPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">企業的 1%</div><h2>同一個企業，可以分享不同形式的 1%。</h2></div><p>用途先確認，再進入對的位置。公益資源、共享所、會員禮遇彼此分流。</p></div><div className="portalGrid three"><article><small>公益關懷</small><h3>公益需求</h3><p>物資、服務、場地、員工人力與專業，依真實需求媒合。</p></article><article><small>資源連結</small><h3>工作 × 人才 × 專業</h3><p>提供職缺、接案、服務、合作與可信任的專業節點。</p></article><article><small>會員禮遇</small><h3>1% 禮遇</h3><p>提供具有實質內容的會員禮遇；不等於公益指定資源。</p></article></div></div></section>
<section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">年度共享標章</div><h2>年度 1% 標章，記錄的是實際共享。</h2></div><p>標章不是付費取得，也不是 RCSCA 官方推薦或 ESG 認證。每年依已完成的真實共享重新核發。</p></div><div className="badgeDemo"><div><OneMark/><strong>1% PARTNER</strong><span>2027 · RCSCA</span></div><p>掃描標章後，只顯示企業當年度公開共享紀錄與可公開 影響力成果，不顯示贊助金額與會員個資。</p></div></div></section>
<section className="portalSection softPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">企業工具</div><h2>企業進來之後，不只看到一張標章。</h2></div></div><div className="portalGrid three"><article><h3>影響力成果</h3><p>年度共享足跡、參與人次、志工時數、合作紀錄與成果素材。</p><a href="/1percent-partner/impact">查看企業成果 →</a></article><article><h3>1% Network</h3><p>查看自己的產業節點、目前夥伴與區域缺口。</p><a href="/1percent-network">進入 1% NETWORK →</a></article><article><h3>ESG 素材</h3><p>可整理成果資料，但 ESG 是參與後的結果，不是公益合作的交換條件。</p></article></div></div></section>
</main>}
