'use client';
import SiteHeader from '../SiteHeader';
import {useMemo,useState} from 'react';
const data=[
 {name:'室內設計',count:3,region:'台北 2 · 新北 1',areas:['台北','新北'],names:['A Space','B Design','C Studio'],offers:['空間諮詢','公益專案支援'],state:'active'},
 {name:'餐飲',count:8,region:'台北 4 · 新北 3 · 桃園 1',areas:['台北','新北','桃園'],names:['示意餐飲夥伴 A','示意餐飲夥伴 B','示意餐飲夥伴 C'],offers:['餐食資源','活動支援'],state:'active'},
 {name:'法律',count:1,region:'台北 1',areas:['台北'],names:['示意法律夥伴'],offers:['法律諮詢'],state:'scarce'},
 {name:'旅宿',count:4,region:'台北 1 · 台中 1 · 南投 1 · 高雄 1',areas:['台北','台中','南投','高雄'],names:['示意旅宿夥伴 A','示意旅宿夥伴 B'],offers:['住宿資源','活動合作'],state:'active'},
 {name:'交通運輸',count:0,region:'目前無節點',areas:[],names:[],offers:[],state:'empty'},
 {name:'寵物服務',count:0,region:'目前無節點',areas:[],names:[],offers:[],state:'empty'},
 {name:'醫療照護',count:1,region:'新北 1',areas:['新北'],names:['示意照護夥伴'],offers:['健康專業'],state:'scarce'},
 {name:'教育',count:2,region:'台北 1 · 桃園 1',areas:['台北','桃園'],names:['示意教育夥伴 A','示意教育夥伴 B'],offers:['教學','陪伴'],state:'active'}
];
export default function Network(){const [sel,setSel]=useState(0);const [filter,setFilter]=useState<'all'|'scarce'|'empty'>('all');const visible=useMemo(()=>data.map((x,i)=>({...x,i})).filter(x=>filter==='all'||x.state===filter),[filter]);const d=data[sel];return <main className="networkPage">
<SiteHeader/>
<section className="networkHero"><div className="portalWrap"><div className="eyebrow">1% NETWORK · 共享專業網絡</div><h1>每一種專業，都可能成為某個人的 1%。</h1><p>快速看見哪些專業已經連上、有哪些企業與店家，以及哪一塊仍在等待第一個 1%。</p><div className="networkStats"><span><b>8</b> 產業節點</span><span><b>19</b> 目前夥伴</span><span><b>2</b> 稀缺產業</span><span><b>2</b> 等待加入</span></div></div></section>
<section className="networkMapSection"><div className="portalWrap"><div className="networkFilter"><span>篩選</span>{[['all','全部'],['scarce','稀缺'],['empty','等待加入']].map(x=><button key={x[0]} className={filter===x[0]?'active':''} onClick={()=>setFilter(x[0] as any)}>{x[1]}</button>)}</div><div className="networkWorkbench"><div className="networkMap"><div className="netCenter"><b>1</b><i>%</i><small>共享網絡</small></div>{visible.map((x,order)=><button key={x.name} onClick={()=>setSel(x.i)} className={`industryNode node-${x.i+1} ${x.state} ${sel===x.i?'selected':''}`}><b>{x.name}</b><span>{x.count?`${x.count} 家夥伴`:'等待第一個 1%'}</span></button>)}<svg className="netLines" viewBox="0 0 800 650" preserveAspectRatio="none"><g>{[[400,325,170,95],[400,325,395,55],[400,325,650,120],[400,325,700,330],[400,325,625,545],[400,325,390,590],[400,325,125,520],[400,325,90,290]].map((l,i)=><line key={i} x1={l[0]} y1={l[1]} x2={l[2]} y2={l[3]}/>)}</g></svg></div><aside className="networkDetail"><small>{d.state==='empty'?'等待加入':d.state==='scarce'?'目前稀缺':'已連結'}</small><h2>{d.name}</h2><strong>{d.count} 家企業／店家</strong><p>{d.region}</p>{d.names.length?<><div className="partnerNames">{d.names.map(n=><span key={n}>{n}</span>)}</div><div className="networkOffers"><small>他們正在分享的 1%</small>{d.offers.map(o=><b key={o}>{o}</b>)}</div></>:<div className="emptyInvite"><b>成為這個產業的第一個 1%。</b><p>沒有獨家名額，也不販售席位；你的專業只是把這塊共享網絡補起來。</p></div>}<a className="networkCta" href={d.count?'/1percent-network/directory':'/1percent-network/join'}>{d.count?'查看公開夥伴 →':'加入這個節點 →'}</a></aside></div></div></section>
<section className="networkQuickActions"><div className="portalWrap"><a href="/1percent-network/directory"><b>查看目前夥伴</b><span>依產業、地區或名稱快速搜尋 →</span></a><a href="/1percent-network/join"><b>加入 1% Network</b><span>把自己的專業補進共享網絡 →</span></a></div></section>
<section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">公開資訊 × 會員權限</div><h2>公開看網絡；深入連結要有權限。</h2></div><p>一般參觀者可以看產業與公開企業；共享夥伴可以留下自己的專業；RCSCA 正式會員才能使用生活找人與工作／人才深層媒合。</p></div><div className="portalGrid three"><article><small>一般參觀者</small><h3>看見網絡</h3><p>查看產業、數量、公開企業與缺口。</p></article><article><small>共享夥伴</small><h3>留下專業</h3><p>建立自己的專業節點與可公開資訊。</p></article><article><small>RCSCA 正式會員</small><h3>進入深層連結</h3><p>生活找人、工作、人才與雙方同意後的聯絡交換。</p></article></div></div></section>
<section className="networkQuickActions"><div className="portalWrap"><a href="/1percent-network/matches"><b>我的媒合</b><span>查看正在尋找、正在提供與工作機會的媒合狀態。</span></a><a href="/1percent-network/directory"><b>公開夥伴</b><span>查看目前已加入並同意公開的企業、店家與專業節點。</span></a></div></section></main>}
