'use client';
import {useEffect,useState} from 'react';import SiteHeader from '../../SiteHeader';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type R={id:string;point_cost:number;status:string;redemption_code:string|null;created_at:string;updated_at:string;reward_catalog:{title:string}|null};
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'MY 1% · 共享所',title:'我的兌換與核銷進度。',lead:'只有核准時才扣除共享點；XP 與公益參與紀錄不受兌換影響。',loading:'正在讀取…',signin:'請先登入',signinLead:'登入後才能查看自己的兌換紀錄。',login:'前往登入 →',market:'共享所',fallback:'共享回饋',points:'共享點',code:'兌換碼：',empty:'目前沒有兌換紀錄。',emptyLead:'符合條件後，可從 1% 共享所送出申請。',go:'前往共享所 →',labels:{submitted:'審核中',approved:'已核准',completed:'已完成',rejected:'未通過'}},
 en:{eye:'MY 1% · Share Market',title:'My redemption and fulfillment progress.',lead:'Sharing Points are deducted only after approval. XP and community participation records are unaffected.',loading:'Loading…',signin:'Please sign in',signinLead:'Sign in to view your redemption history.',login:'Go to sign in →',market:'Share Market',fallback:'Sharing reward',points:'Sharing Points',code:'Redemption code: ',empty:'No redemption history yet.',emptyLead:'Once eligible, you can submit a request through the 1% Share Market.',go:'Go to Share Market →',labels:{submitted:'Under review',approved:'Approved',completed:'Completed',rejected:'Not approved'}},
 ja:{eye:'MY 1% · シェアマーケット',title:'自分の交換・利用状況。',lead:'共有ポイントは承認時にのみ差し引かれます。XPと公益参加記録には影響しません。',loading:'読み込み中…',signin:'ログインしてください',signinLead:'ログイン後に交換履歴を確認できます。',login:'ログインへ →',market:'シェアマーケット',fallback:'共有特典',points:'共有ポイント',code:'交換コード：',empty:'交換履歴はまだありません。',emptyLead:'条件を満たすと、1%シェアマーケットから申請できます。',go:'シェアマーケットへ →',labels:{submitted:'審査中',approved:'承認済み',completed:'完了',rejected:'非承認'}},
 ko:{eye:'MY 1% · 공유 마켓',title:'나의 교환 및 사용 진행 상황.',lead:'공유 포인트는 승인 시에만 차감되며 XP와 공익 참여 기록에는 영향을 주지 않습니다.',loading:'불러오는 중…',signin:'로그인이 필요합니다',signinLead:'로그인 후 교환 기록을 확인할 수 있습니다.',login:'로그인으로 →',market:'공유 마켓',fallback:'공유 혜택',points:'공유 포인트',code:'교환 코드: ',empty:'아직 교환 기록이 없습니다.',emptyLead:'조건을 충족하면 1% 공유 마켓에서 신청할 수 있습니다.',go:'공유 마켓으로 →',labels:{submitted:'심사 중',approved:'승인됨',completed:'완료',rejected:'승인되지 않음'}}
};
const dateLocale:Record<Locale,string>={'zh-Hant':'zh-TW',en:'en-US',ja:'ja-JP',ko:'ko-KR'};
export default function Redemptions(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<R[]>([]),[loading,setLoading]=useState(true),[signed,setSigned]=useState(false);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session){setLoading(false);return}setSigned(true);const{data}=await s.from('reward_redemptions').select('id,point_cost,status,redemption_code,created_at,updated_at,reward_catalog(title)').eq('user_id',session.user.id).order('created_at',{ascending:false});setRows((data||[]) as any);setLoading(false)})()},[locale]);return <main className="flowPage"><SiteHeader/><section className="flowHero"><div className="portalWrap"><div className="eyebrow">{c.eye}</div><h1>{c.title}</h1><p>{c.lead}</p></div></section><section className="portalSection"><div className="portalWrap">{loading?<p>{c.loading}</p>:!signed?<div className="privacyCallout"><strong>{c.signin}</strong><p>{c.signinLead}</p><a href="/login">{c.login}</a></div>:rows.length?<div className="stateList">{rows.map(r=><article key={r.id}><div className="stateMeta"><small>{c.market}</small><span>{new Date(r.created_at).toLocaleDateString(dateLocale[locale])}</span></div><h3>{r.reward_catalog?.title||c.fallback}</h3><div className="stateRow"><span className={`statusChip status-${r.status}`}>{c.labels[r.status]||r.status}</span><span>{r.point_cost} {c.points}</span></div>{r.redemption_code&&<p>{c.code}<strong>{r.redemption_code}</strong></p>}</article>)}</div>:<div className="privacyCallout"><strong>{c.empty}</strong><p>{c.emptyLead}</p><a href="/share-market">{c.go}</a></div>}</div></section></main>}
