'use client';
import {useI18n} from '../i18n';
const copy:any={
 members:{zh:['Admin · 會員與身份','正式會員身份與身份驗證，在同一個營運工作區完成。','會籍只決定正式會員權限，不直接產生 XP 或共享點。'],en:['Admin · Members & Identity','Manage membership status and identity verification in one operations workspace.','Membership controls member access only; it does not directly generate XP or Sharing Points.'],ja:['Admin · 会員と本人確認','正式会員の状態と本人確認を、ひとつの運用画面で管理します。','会員資格は権限のみを決め、XPや共有ポイントを直接付与しません。'],ko:['Admin · 회원 및 신원','정식 회원 상태와 신원 확인을 하나의 운영 화면에서 관리합니다.','회원 자격은 권한만 결정하며 XP나 공유 포인트를 직접 생성하지 않습니다.']},
 access:{zh:['RCSCA ADMIN · 權限治理','權限要能分工，也要能追溯。','最高管理者可配置後台角色；所有授權與撤權都會留下稽核紀錄。'],en:['RCSCA ADMIN · Access Governance','Permissions must support delegation and remain traceable.','Authorized administrators can assign back-office roles; every grant and revocation leaves an audit trail.'],ja:['RCSCA ADMIN · 権限管理','権限は分担でき、追跡できる必要があります。','権限を持つ管理者が管理画面の役割を設定し、付与・解除はすべて監査記録に残ります。'],ko:['RCSCA ADMIN · 권한 관리','권한은 분담할 수 있어야 하고 추적 가능해야 합니다.','권한 있는 관리자가 백오피스 역할을 설정하며 모든 부여·회수는 감사 기록에 남습니다.']},
 partners:{zh:['Admin · 企業夥伴','企業身份、共享與年度標章，在同一個工作區管理。','審核企業資格、共享內容與公開範圍，保留可追溯的營運紀錄。'],en:['Admin · Organization Partners','Manage organization identity, sharing and annual badges in one workspace.','Review eligibility, sharing content and public visibility with traceable operations records.'],ja:['Admin · 企業パートナー','企業確認、共有、年次バッジをひとつの画面で管理します。','資格、共有内容、公開範囲を審査し、追跡可能な運用記録を残します。'],ko:['Admin · 기업 파트너','기업 신원, 공유 및 연간 배지를 하나의 화면에서 관리합니다.','자격, 공유 내용과 공개 범위를 심사하고 추적 가능한 운영 기록을 남깁니다.']},
 network:{zh:['Admin · 1% Network','媒合要能推進，也要保護雙方資料。','管理需求、回應與媒合進度；聯絡資料仍以雙方同意為前提。'],en:['Admin · 1% Network','Matching should move forward without exposing either side’s data.','Manage requests, responses and matching progress; contact exchange still requires mutual consent.'],ja:['Admin · 1% Network','マッチングを進めながら、双方の情報を守ります。','依頼、応答、進捗を管理し、連絡先交換は双方の同意を前提とします。'],ko:['Admin · 1% Network','매칭은 진행하되 양측의 정보는 보호해야 합니다.','요청, 응답과 진행 상황을 관리하며 연락처 교환은 양측 동의를 전제로 합니다.']},
 cases:{zh:['Admin · 受保護需求','需要被接住，也需要被妥善保護。','敏感需求與內部工作筆記依權限分層，不進入公開網站。'],en:['Admin · Protected Requests','Support needs must be handled—and protected—with care.','Sensitive requests and internal case notes are permission-layered and never published publicly.'],ja:['Admin · 保護対象の依頼','支援につなげると同時に、適切に保護します。','機微な依頼と内部メモは権限で分離し、公開サイトには掲載しません。'],ko:['Admin · 보호 요청','필요는 연결되어야 하고 동시에 안전하게 보호되어야 합니다.','민감한 요청과 내부 메모는 권한별로 분리되며 공개 사이트에 노출되지 않습니다.']},
 rewards:{zh:['Admin · 共享所','共享回饋要能管理，也不能改變公益資源的用途。','管理回饋目錄、條件、庫存與兌換；公益指定資源維持完全分離。'],en:['Admin · Sharing Rewards','Rewards need operational control without changing the purpose of care resources.','Manage catalog, eligibility, inventory and redemptions while keeping designated care resources fully separate.'],ja:['Admin · 共有リワード','リワードを運用しながら、公益資源の用途は変えません。','カタログ、条件、在庫、交換を管理し、公益指定資源は完全に分離します。'],ko:['Admin · 공유 리워드','리워드는 운영하되 공익 자원의 용도는 바꾸지 않습니다.','카탈로그, 조건, 재고와 교환을 관리하며 공익 지정 자원은 완전히 분리합니다.']},
 outcomes:{zh:['Admin · 成果工作區','成果要能整理，也要能證明從哪裡來。','只有核實完成且符合公開條件的資料，才能進入對外成果。'],en:['Admin · Outcomes Workspace','Outcomes should be organized and traceable to their source.','Only verified completed records that meet visibility rules can become public outcomes.'],ja:['Admin · 成果ワークスペース','成果は整理するだけでなく、根拠まで追跡できる必要があります。','完了確認済みで公開条件を満たす記録だけを対外成果に反映します。'],ko:['Admin · 성과 작업공간','성과는 정리될 뿐 아니라 출처까지 추적 가능해야 합니다.','완료가 확인되고 공개 조건을 충족한 기록만 외부 성과에 반영됩니다.']},
 operations:{zh:['RCSCA 後台作業','前台可以簡單，後台必須可追溯。','公益、企業、媒合與受保護個案依管理角色分流；重要操作保留 Audit Log。'],en:['RCSCA Operations','The front end can stay simple; operations must remain traceable.','Care, organizations, matching and protected cases are routed by admin role, with important actions preserved in the Audit Log.'],ja:['RCSCA 運用管理','フロントはシンプルでも、運用は追跡可能でなければなりません。','公益、企業、マッチング、保護対象案件を役割別に処理し、重要操作はAudit Logに残します。'],ko:['RCSCA 운영 관리','사용자 화면은 단순해도 운영은 추적 가능해야 합니다.','공익, 기업, 매칭과 보호 사례를 관리자 역할별로 처리하고 중요 작업은 Audit Log에 남깁니다.']}
};
export default function AdminPageIntro({section}:{section:keyof typeof copy}){const {locale}=useI18n();const lang=locale==='zh-Hant'?'zh':locale;const c=copy[section]?.[lang]||copy[section]?.zh;return <section className="adminHero"><div className="portalWrap"><div className="eyebrow">{c[0]}</div><h1>{c[1]}</h1><p>{c[2]}</p></div></section>}
