'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';
import type {Database} from '../../../lib/database.types';
import EnterpriseShareComposer from './EnterpriseShareComposer';
import {Locale,useI18n} from '../../i18n';

type Enterprise={id:string;display_name:string|null;legal_name:string;industry:string|null;region:string|null;public_description:string|null;status:string};
type Share={id:string;title:string;share_type:Database['public']['Enums']['share_type'];status:string;public_result:boolean;description?:string|null};
type Request={id:string;title:string;request_kind:string;status:string};
const statusLabel:Record<string,string>={draft:'草稿',submitted:'已送出',under_review:'審核中',needs_info:'待補資料',approved:'已核准',matched:'媒合中',completed:'已完成',rejected:'未通過',cancelled:'已取消'};
const shareLabel:Record<string,string>={care:'公益關懷',connection:'資源連結',benefit:'會員禮遇',job:'工作機會',professional:'專業共享',resource:'資源共享'};

const dashboardCopy:Record<Locale,any>={
 'zh-Hant':{status:statusLabel,share:shareLabel,signin:'請先登入企業帳號',identityFailed:'目前無法讀取企業身份',unlinked:'這個帳號尚未連結 1% 企業共享夥伴',loading:'正在讀取企業共享狀態…',entry:'企業管理入口',guestLead:'企業帳號核准並完成連結後，才會看到內部共享與媒合紀錄。',login:'登入 →',active:'進行中 ESG 案件',activeLead:'目前正在評估或執行',priority:'需優先處理',priorityLead:'已超過下一步預計日期',approved:'已核准成果',approvedLead:'已完成 RCSCA 成果審核',deliverable:'可正式交付',deliverableLead:'品質與證據鏈均完成',sdg:'SDG 涵蓋',sdgLead:'已核准成果涵蓋項目',viewer:'目前企業角色：查看者。你可以查看企業進度與成果，但不能新增、取消、補件或修改企業資料。',identity:'企業身份',industryMissing:'產業待補',regionMissing:'地區待補',yearShares:'本年度共享項目',yearSharesLead:'公益／連結／禮遇分流記錄',requests:'Network 需求',requestsLead:'由企業帳號真實讀取',pending:'待處理',pendingLead:'審核／補資料中的項目',ledger:'企業共享紀錄',ledgerTitle:'每一筆都知道目前在哪一步。',ledgerLead:'不以贊助金額排序。企業可提出共享內容，但不能自行核准或把內容直接公開。',type:'類型',content:'內容',state:'狀態',public:'公開',published:'已公開',private:'未公開',empty:'目前還沒有企業共享紀錄。'},
 'en':{status:{draft:'Draft',submitted:'Submitted',under_review:'Under review',needs_info:'More information needed',approved:'Approved',matched:'Matching',completed:'Completed',rejected:'Not approved',cancelled:'Cancelled'},share:{care:'Community care',connection:'Resource connection',benefit:'Member benefit',job:'Job opportunity',professional:'Professional sharing',resource:'Resource sharing'},signin:'Sign in with your enterprise account',identityFailed:'Unable to read enterprise identity',unlinked:'This account is not linked to a 1% enterprise partner',loading:'Loading enterprise sharing status…',entry:'Enterprise management',guestLead:'Internal sharing and matching records appear after the enterprise account is approved and linked.',login:'Sign in →',active:'Active ESG cases',activeLead:'Currently under review or in progress',priority:'Needs attention',priorityLead:'Past the expected next-action date',approved:'Approved outcomes',approvedLead:'RCSCA outcome review completed',deliverable:'Ready to deliver',deliverableLead:'Quality and evidence chain completed',sdg:'SDG coverage',sdgLead:'Areas covered by approved outcomes',viewer:'Enterprise role: viewer. You may view progress and outcomes, but cannot create, cancel, resubmit, or edit enterprise data.',identity:'Enterprise identity',industryMissing:'Industry not set',regionMissing:'Region not set',yearShares:'Sharing items this year',yearSharesLead:'Care / connections / benefits recorded separately',requests:'Network requests',requestsLead:'Read from the linked enterprise account',pending:'Pending',pendingLead:'Items under review or awaiting information',ledger:'Enterprise sharing records',ledgerTitle:'Every item shows its current step.',ledgerLead:'Items are not ranked by sponsorship amount. Enterprises may submit sharing content but cannot approve or publish it themselves.',type:'Type',content:'Content',state:'Status',public:'Public',published:'Published',private:'Not public',empty:'No enterprise sharing records yet.'},
 'ja':{status:{draft:'下書き',submitted:'提出済み',under_review:'審査中',needs_info:'追加情報が必要',approved:'承認済み',matched:'マッチング中',completed:'完了',rejected:'未承認',cancelled:'取消済み'},share:{care:'公益ケア',connection:'資源連携',benefit:'会員特典',job:'仕事の機会',professional:'専門性の共有',resource:'資源共有'},signin:'企業アカウントでログインしてください',identityFailed:'企業情報を読み込めません',unlinked:'このアカウントは1%企業パートナーに未連携です',loading:'企業共有状況を読み込み中…',entry:'企業管理ページ',guestLead:'企業アカウントの承認・連携後に、内部の共有とマッチング記録を確認できます。',login:'ログイン →',active:'進行中のESG案件',activeLead:'現在審査中または実行中',priority:'優先対応',priorityLead:'次の対応予定日を超過',approved:'承認済み成果',approvedLead:'RCSCA成果審査完了',deliverable:'正式納品可能',deliverableLead:'品質と証拠チェーンが完了',sdg:'SDG範囲',sdgLead:'承認済み成果の対象項目',viewer:'企業ロール：閲覧者。進捗と成果は閲覧できますが、追加・取消・再提出・企業情報の変更はできません。',identity:'企業情報',industryMissing:'業種未設定',regionMissing:'地域未設定',yearShares:'今年度の共有項目',yearSharesLead:'公益／連携／特典を分けて記録',requests:'Network依頼',requestsLead:'連携済み企業アカウントから取得',pending:'対応待ち',pendingLead:'審査中／追加情報待ち',ledger:'企業共有記録',ledgerTitle:'すべての項目で現在の段階が分かります。',ledgerLead:'支援額では順位付けしません。企業は内容を提出できますが、自ら承認・公開することはできません。',type:'種類',content:'内容',state:'状況',public:'公開',published:'公開済み',private:'非公開',empty:'企業共有記録はまだありません。'},
 'ko':{status:{draft:'초안',submitted:'제출됨',under_review:'검토 중',needs_info:'추가 정보 필요',approved:'승인됨',matched:'매칭 중',completed:'완료',rejected:'승인되지 않음',cancelled:'취소됨'},share:{care:'공익 돌봄',connection:'자원 연결',benefit:'회원 혜택',job:'일자리',professional:'전문성 공유',resource:'자원 공유'},signin:'기업 계정으로 로그인해 주세요',identityFailed:'기업 정보를 불러올 수 없습니다',unlinked:'이 계정은 아직 1% 기업 파트너와 연결되지 않았습니다',loading:'기업 공유 상태 불러오는 중…',entry:'기업 관리',guestLead:'기업 계정이 승인되고 연결된 후 내부 공유 및 매칭 기록을 볼 수 있습니다.',login:'로그인 →',active:'진행 중 ESG 건',activeLead:'현재 검토 또는 실행 중',priority:'우선 처리 필요',priorityLead:'다음 단계 예정일 초과',approved:'승인된 성과',approvedLead:'RCSCA 성과 검토 완료',deliverable:'정식 전달 가능',deliverableLead:'품질 및 증거 체인 완료',sdg:'SDG 범위',sdgLead:'승인된 성과의 해당 항목',viewer:'기업 역할: 조회자. 진행과 성과를 볼 수 있지만 추가, 취소, 보완 제출 또는 기업 정보 수정은 할 수 없습니다.',identity:'기업 정보',industryMissing:'업종 미설정',regionMissing:'지역 미설정',yearShares:'올해 공유 항목',yearSharesLead:'공익／연결／혜택을 분리 기록',requests:'Network 요청',requestsLead:'연결된 기업 계정에서 조회',pending:'처리 대기',pendingLead:'검토 또는 정보 보완 중인 항목',ledger:'기업 공유 기록',ledgerTitle:'각 항목의 현재 단계를 확인할 수 있습니다.',ledgerLead:'후원 금액으로 순위를 정하지 않습니다. 기업은 공유 내용을 제출할 수 있지만 직접 승인하거나 공개할 수 없습니다.',type:'유형',content:'내용',state:'상태',public:'공개',published:'공개됨',private:'비공개',empty:'아직 기업 공유 기록이 없습니다.'}
};

const actionCopy:Record<Locale,any>={
 'zh-Hant':{cancelConfirm:'確定取消這筆尚未核准的企業共享？',cancelFailed:'目前無法取消這筆共享。',cancelled:'已取消這筆共享。',processing:'處理中…',cancel:'取消申請',needsInfo:'RCSCA 要求補資料',detailPlaceholder:'補充適用對象、範圍、限制或交付方式',resubmitFailed:'重新送審失敗，請稍後再試。',resubmitted:'已補件並重新送審。',submitting:'送出中…',resubmit:'補件並重新送審',unpublishNote:'企業申請取消這筆公開共享。',updateNote:'企業申請修改已核准共享內容。',pending:'已有待審核變更申請。',requestFailed:'目前無法送出申請。',unpublishSent:'已送出下架申請。',updateSent:'已送出修改申請。',collapse:'收起修改',requestEdit:'申請修改',requestUnpublish:'申請停止公開',approvedGuard:'已核准內容不直接覆寫',submitReview:'送出修改審核',profileNote:'企業申請更新公開基本資料',profilePending:'已有待審核的企業資料變更申請。',profileFailed:'目前無法送出企業資料修改申請。',profileSent:'已送出企業基本資料修改申請；核准前仍維持目前公開版本。',profileEye:'企業基本資料',profileTitle:'公開資料修改先審核，再更新。',collapseShort:'收起',displayName:'顯示名稱',industry:'產業',region:'地區',unset:'尚未設定',intro:'公開介紹',publicName:'企業公開名稱',publicIntro:'可公開的企業介紹，不放私人聯絡資料。',legalGuard:'統一編號、法定名稱與企業身份狀態不開放前台自行修改；必要變更由 RCSCA 後台另行核實。'},
 'en':{cancelConfirm:'Cancel this enterprise sharing item before approval?',cancelFailed:'Unable to cancel this sharing item.',cancelled:'Sharing item cancelled.',processing:'Processing…',cancel:'Cancel application',needsInfo:'RCSCA requested more information',detailPlaceholder:'Add eligibility, scope, limits, or delivery details',resubmitFailed:'Resubmission failed. Please try again later.',resubmitted:'Additional information submitted for review.',submitting:'Submitting…',resubmit:'Add information and resubmit',unpublishNote:'Enterprise requests removal of this public sharing item.',updateNote:'Enterprise requests changes to approved sharing content.',pending:'A change request is already pending review.',requestFailed:'Unable to submit the request.',unpublishSent:'Unpublish request submitted.',updateSent:'Change request submitted.',collapse:'Close editor',requestEdit:'Request changes',requestUnpublish:'Request unpublish',approvedGuard:'Approved content is not overwritten directly',submitReview:'Submit changes for review',profileNote:'Enterprise requests an update to its public profile',profilePending:'An enterprise profile change request is already pending review.',profileFailed:'Unable to submit the enterprise profile change request.',profileSent:'Enterprise profile change submitted. The current public version remains until approval.',profileEye:'Enterprise profile',profileTitle:'Review public-data changes before updating.',collapseShort:'Close',displayName:'Display name',industry:'Industry',region:'Region',unset:'Not set',intro:'Public introduction',publicName:'Public enterprise name',publicIntro:'Public enterprise introduction; do not include private contact details.',legalGuard:'Tax ID, legal name, and enterprise identity status cannot be edited here. Necessary changes are verified separately by RCSCA.'},
 'ja':{cancelConfirm:'未承認の企業共有申請を取り消しますか？',cancelFailed:'この共有申請を取り消せません。',cancelled:'共有申請を取り消しました。',processing:'処理中…',cancel:'申請を取消',needsInfo:'RCSCAから追加情報の依頼',detailPlaceholder:'対象、範囲、制限、提供方法を補足',resubmitFailed:'再提出できません。後ほど再度お試しください。',resubmitted:'情報を補足して再審査へ送信しました。',submitting:'送信中…',resubmit:'情報を補足して再提出',unpublishNote:'企業がこの公開共有の非公開化を申請。',updateNote:'企業が承認済み共有内容の変更を申請。',pending:'審査中の変更申請があります。',requestFailed:'申請を送信できません。',unpublishSent:'非公開申請を送信しました。',updateSent:'変更申請を送信しました。',collapse:'編集を閉じる',requestEdit:'変更を申請',requestUnpublish:'非公開を申請',approvedGuard:'承認済み内容は直接上書きされません',submitReview:'変更を審査へ送信',profileNote:'企業が公開基本情報の更新を申請',profilePending:'審査中の企業情報変更申請があります。',profileFailed:'企業情報の変更申請を送信できません。',profileSent:'企業基本情報の変更を申請しました。承認までは現在の公開版が維持されます。',profileEye:'企業基本情報',profileTitle:'公開情報は審査後に更新します。',collapseShort:'閉じる',displayName:'表示名',industry:'業種',region:'地域',unset:'未設定',intro:'公開紹介',publicName:'企業の公開名称',publicIntro:'公開可能な企業紹介。個人連絡先は入力しないでください。',legalGuard:'法人番号、法定名称、企業の本人確認状況はここでは変更できません。必要な変更はRCSCAが別途確認します。'},
 'ko':{cancelConfirm:'아직 승인되지 않은 기업 공유 신청을 취소할까요?',cancelFailed:'이 공유 신청을 취소할 수 없습니다.',cancelled:'공유 신청을 취소했습니다.',processing:'처리 중…',cancel:'신청 취소',needsInfo:'RCSCA 추가 정보 요청',detailPlaceholder:'대상, 범위, 제한 또는 제공 방법을 보완',resubmitFailed:'다시 제출하지 못했습니다. 잠시 후 다시 시도해 주세요.',resubmitted:'정보를 보완하여 다시 검토 요청했습니다.',submitting:'제출 중…',resubmit:'정보 보완 후 다시 제출',unpublishNote:'기업이 이 공개 공유의 비공개 전환을 신청함.',updateNote:'기업이 승인된 공유 내용의 수정을 신청함.',pending:'이미 검토 중인 변경 신청이 있습니다.',requestFailed:'신청을 제출할 수 없습니다.',unpublishSent:'비공개 신청을 제출했습니다.',updateSent:'수정 신청을 제출했습니다.',collapse:'수정 닫기',requestEdit:'수정 신청',requestUnpublish:'비공개 신청',approvedGuard:'승인된 내용은 바로 덮어쓰지 않습니다',submitReview:'수정 검토 제출',profileNote:'기업 공개 기본 정보 수정 신청',profilePending:'이미 검토 중인 기업 정보 변경 신청이 있습니다.',profileFailed:'기업 정보 수정 신청을 제출할 수 없습니다.',profileSent:'기업 기본 정보 수정 신청을 제출했습니다. 승인 전에는 현재 공개 버전이 유지됩니다.',profileEye:'기업 기본 정보',profileTitle:'공개 정보는 검토 후 업데이트합니다.',collapseShort:'닫기',displayName:'표시 이름',industry:'업종',region:'지역',unset:'미설정',intro:'공개 소개',publicName:'기업 공개 이름',publicIntro:'공개 가능한 기업 소개이며 개인 연락처는 입력하지 마세요.',legalGuard:'사업자번호, 법적 명칭 및 기업 신원 상태는 여기에서 직접 수정할 수 없습니다. 필요한 변경은 RCSCA가 별도로 확인합니다.'}
};



function ShareActions({share,onSaved}:{share:Share;onSaved:()=>void}){
 const {locale}=useI18n();const c=actionCopy[locale];
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function cancel(){if(!confirm(c.cancelConfirm))return;setBusy(true);const s=getSupabaseBrowserClient();const {error}=await s.rpc('enterprise_cancel_share',{p_share_id:share.id});setNotice(error?c.cancelFailed:c.cancelled);setBusy(false);if(!error)onSaved()}
 if(!['draft','submitted','under_review','needs_info'].includes(share.status))return null;
 return <div className="shareInlineActions"><button className="secondaryAction" disabled={busy} onClick={cancel}>{busy?c.processing:c.cancel}</button>{notice&&<span>{notice}</span>}</div>
}

function ShareNeedsInfo({share,onSaved}:{share:Share;onSaved:()=>void}){
 const {locale}=useI18n();const c=actionCopy[locale];
 const [title,setTitle]=useState(share.title),[description,setDescription]=useState(share.description||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  async function resubmit(){if(!title.trim())return;setBusy(true);const s=getSupabaseBrowserClient();const {error}=await s.rpc('enterprise_resubmit_share',{p_share_id:share.id,p_title:title.trim(),p_description:description.trim()||undefined,p_share_type:share.share_type});setNotice(error?c.resubmitFailed:c.resubmitted);setBusy(false);if(!error)onSaved()}
 return <div className="shareCorrection"><small>{c.needsInfo}</small><input value={title} onChange={e=>setTitle(e.target.value)}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={c.detailPlaceholder}/><button disabled={busy} onClick={resubmit}>{busy?c.submitting:c.resubmit}</button>{notice&&<span>{notice}</span>}</div>
}


function ApprovedShareChange({share,onSaved}:{share:Share;onSaved:()=>void}){
 const {locale}=useI18n();const c=actionCopy[locale];
 const [editing,setEditing]=useState(false),[title,setTitle]=useState(share.title),[description,setDescription]=useState(share.description||''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function submit(action:'update'|'unpublish'){setBusy(true);const s=getSupabaseBrowserClient();const proposed=action==='update'?{title:title.trim(),description:description.trim(),public_result:share.public_result}:{};const {error}=await s.rpc('request_approved_record_change',{p_subject_type:'enterprise_share',p_subject_id:share.id,p_request_action:action,p_proposed_changes:proposed,p_requester_note:action==='unpublish'?c.unpublishNote:c.updateNote});setNotice(error?(error.message.includes('pending_change_request_exists')?c.pending:c.requestFailed):(action==='unpublish'?c.unpublishSent:c.updateSent));setBusy(false);if(!error){setEditing(false);onSaved()}}
 return <div className="approvedChange"><div className="shareInlineActions"><button className="secondaryAction" onClick={()=>setEditing(v=>!v)}>{editing?c.collapse:c.requestEdit}</button>{share.public_result&&<button className="secondaryAction" disabled={busy} onClick={()=>submit('unpublish')}>{c.requestUnpublish}</button>}</div>{editing&&<div className="shareCorrection"><small>{c.approvedGuard}</small><input value={title} onChange={e=>setTitle(e.target.value)}/><textarea value={description} onChange={e=>setDescription(e.target.value)}/><button disabled={busy||!title.trim()} onClick={()=>submit('update')}>{busy?c.submitting:c.submitReview}</button></div>}{notice&&<span className="formNote">{notice}</span>}</div>
}


function EnterpriseProfileChange({enterprise}:{enterprise:Enterprise}){
 const {locale}=useI18n();const c=actionCopy[locale];
 const [editing,setEditing]=useState(false),[displayName,setDisplayName]=useState(enterprise.display_name||enterprise.legal_name),[industry,setIndustry]=useState(enterprise.industry||''),[region,setRegion]=useState(enterprise.region||''),[description,setDescription]=useState(enterprise.public_description||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function submit(){if(!displayName.trim())return;setBusy(true);const s=getSupabaseBrowserClient();const {error}=await s.rpc('request_enterprise_profile_change',{p_enterprise_id:enterprise.id,p_display_name:displayName.trim(),p_industry:industry.trim(),p_region:region.trim(),p_public_description:description.trim(),p_requester_note:c.profileNote});setNotice(error?(error.message.includes('pending_change_request_exists')?c.profilePending:c.profileFailed):c.profileSent);setBusy(false);if(!error)setEditing(false)}
 return <section className="enterpriseProfilePanel"><div className="sectionHead compact"><div><div className="eyebrow">{c.profileEye}</div><h2>{c.profileTitle}</h2></div><button className="secondaryAction" onClick={()=>setEditing(v=>!v)}>{editing?c.collapseShort:c.requestEdit}</button></div><div className="enterpriseProfileSummary"><p><b>{c.displayName}</b>：{enterprise.display_name||enterprise.legal_name}</p><p><b>{c.industry}</b>：{enterprise.industry||c.unset}</p><p><b>{c.region}</b>：{enterprise.region||c.unset}</p>{enterprise.public_description&&<p><b>{c.intro}</b>：{enterprise.public_description}</p>}</div>{editing&&<div className="shareCorrection"><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder={c.publicName}/><input value={industry} onChange={e=>setIndustry(e.target.value)} placeholder={c.industry}/><input value={region} onChange={e=>setRegion(e.target.value)} placeholder={c.region}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={c.publicIntro}/><button disabled={busy||!displayName.trim()} onClick={submit}>{busy?c.submitting:c.submitReview}</button></div>}{notice&&<p className="formNote">{notice}</p>}<p className="microNote">{c.legalGuard}</p></section>
}

export default function LivePartnerDashboard(){
 const {locale}=useI18n();const c=dashboardCopy[locale];
 const [loading,setLoading]=useState(true); const [enterprise,setEnterprise]=useState<Enterprise|null>(null); const [myRole,setMyRole]=useState('viewer'); const [shares,setShares]=useState<Share[]>([]); const [requests,setRequests]=useState<Request[]>([]); const [summary,setSummary]=useState<any>(null); const [error,setError]=useState('');
 async function reloadShares(){if(!enterprise)return;const s=getSupabaseBrowserClient();const {data}=await s.from('enterprise_shares').select('id,title,share_type,status,public_result,description').eq('enterprise_id',enterprise.id).order('created_at',{ascending:false});setShares((data||[]) as Share[])}
 useEffect(()=>{let alive=true; const supabase=getSupabaseBrowserClient(); (async()=>{const {data:{session}}=await supabase.auth.getSession(); if(!session){if(alive){setError(c.signin);setLoading(false)};return;} const {data:eu,error:euErr}=await supabase.from('enterprise_users').select('enterprise_id,role,enterprises(id,display_name,legal_name,industry,region,public_description,status)').eq('user_id',session.user.id).limit(1).maybeSingle(); if(euErr){if(alive){setError(c.identityFailed);setLoading(false)};return;} const ent=(eu as any)?.enterprises as Enterprise|undefined; if(!ent){if(alive){setError(c.unlinked);setLoading(false)};return;} const [s,r]=await Promise.all([supabase.from('enterprise_shares').select('id,title,share_type,status,public_result,description').eq('enterprise_id',ent.id).order('created_at',{ascending:false}),supabase.from('network_requests').select('id,title,request_kind,status').eq('requester_enterprise_id',ent.id).order('created_at',{ascending:false})]); const {data:sum}=await supabase.from('enterprise_management_summary').select('*').eq('enterprise_id',ent.id).maybeSingle(); if(alive){setEnterprise(ent);setMyRole((eu as any)?.role||'viewer');setShares((s.data||[]) as Share[]);setRequests((r.data||[]) as Request[]);setSummary(sum);setLoading(false)}})(); return()=>{alive=false}},[locale]);
 if(loading)return <div className="liveAccountLoading">{c.loading}</div>;
 if(error)return <div className="liveAccountGuest"><div><small>{c.entry}</small><strong>{error}</strong><p>{c.guestLead}</p></div><Link href="/login">{c.login}</Link></div>;
 const canEdit=myRole==='manager'||myRole==='editor';
 const pending=[...shares.filter(x=>['submitted','under_review','needs_info'].includes(x.status)),...requests.filter(x=>['submitted','under_review','needs_info'].includes(x.status))].length;
 return <>
  {summary&&<div className="executiveSummary"><article><small>{c.active}</small><strong>{summary.active_cases}</strong><span>{c.activeLead}</span></article><article className={summary.overdue_cases>0?'attention':''}><small>{c.priority}</small><strong>{summary.overdue_cases}</strong><span>{c.priorityLead}</span></article><article><small>{c.approved}</small><strong>{summary.approved_outcomes}</strong><span>{c.approvedLead}</span></article><article className="good"><small>{c.deliverable}</small><strong>{summary.deliverable_outcomes}</strong><span>{c.deliverableLead}</span></article><article><small>{c.sdg}</small><strong>{summary.sdg_coverage}</strong><span>{c.sdgLead}</span></article></div>}
  {enterprise&&canEdit&&<EnterpriseProfileChange enterprise={enterprise}/>}
  {enterprise&&!canEdit&&<div className="workflowNotice">{c.viewer}</div>}
  <div className="partnerSummary"><article><small>{c.identity}</small><strong>{enterprise?.display_name||enterprise?.legal_name}</strong><span>{enterprise?.industry||c.industryMissing} · {enterprise?.region||c.regionMissing}</span></article><article><small>{c.yearShares}</small><strong>{shares.length}</strong><span>{c.yearSharesLead}</span></article><article><small>{c.requests}</small><strong>{requests.length}</strong><span>{c.requestsLead}</span></article><article><small>{c.pending}</small><strong>{pending}</strong><span>{c.pendingLead}</span></article></div>
  <div className="sectionHead"><div><div className="eyebrow">{c.ledger}</div><h2>{c.ledgerTitle}</h2></div><p>{c.ledgerLead}</p></div>
  <div className="enterpriseLedger"><div className="elHead"><span>{c.type}</span><span>{c.content}</span><span>{c.state}</span><span>{c.public}</span></div>{shares.length?shares.map(x=><div className="elRow" key={x.id}><span>{c.share[x.share_type]||x.share_type}</span><span>{x.title}</span><span>{c.status[x.status]||x.status}</span><span>{x.public_result?c.published:c.private}</span>{canEdit&&x.status==='needs_info'&&<ShareNeedsInfo share={x} onSaved={reloadShares}/>} {canEdit&&<ShareActions share={x} onSaved={reloadShares}/>} {canEdit&&x.status==='approved'&&<ApprovedShareChange share={x} onSaved={reloadShares}/>}</div>):<div className="emptyData">{c.empty}</div>}</div>
  {enterprise&&canEdit&&<EnterpriseShareComposer enterpriseId={enterprise.id} onSaved={reloadShares}/>}
 </>;
}
