'use client';
import SiteHeader from '../SiteHeader';
import {useI18n, type Locale} from '../i18n';

type Activity={id:string;code:string;name:string;category:string;status:string;public_summary:string|null;starts_at:string|null;ends_at:string|null};
const copy:Record<Locale,Record<string,string>>={
'zh-Hant':{eyebrow:'關懷 · 50%',hero:'需要被看見的，不只有一種樣子。',lead:'偏鄉、育幼院、弱勢家庭、單親、年長、新住民、身障，以及制度暫時接不到但確有真實缺口的人，都可能在某個時間需要被接住。',now:'現在進行中',nowTitle:'現在正在發生。',nowLead:'正式公開的公益行動會由核准資料帶入；草稿與內部活動不會出現在公開網站。',care:'關懷行動',sharing:'共享行動',detailPending:'詳細內容整理中',view:'查看活動 →',status:'目前狀態',none:'尚無正式公開中的活動',noneLead:'目前沒有符合公開條件的進行中活動。草稿、內部活動與未核准內容不會出現在公開網站。',privacy:'關懷 ≠ 消費弱勢',privacyLead:'不以弱勢處境換取參與，不要求特殊保護個案成為宣傳素材。',join:'我想參與',joinTitle:'加入目前的公益行動',joinLead:'先留下參與意願，交付方式可依活動規則處理 →',need:'我有真實需求',needTitle:'提出需要被接住的缺口',needLead:'不公開求助故事，先進入 RCSCA 內部評估 →',archive:'查看歷年關懷行動 →',noLabel:'需求不是標籤',noLabelTitle:'我們看的是此刻的缺口，不是替人貼上永久身份。',back:'回到善循環',backTitle:'被接住，不代表被永久定義。',backLead:'當生活重新站穩，有能力時，可以用自己的方式再次進入善循環；不是還債，也不要求等值。',cycle:'了解善循環 →'},
'en':{eyebrow:'Care · 50%',hero:'Need does not come in only one form.',lead:'Rural communities, children in residential care, families under financial stress, single-parent households, older adults, new immigrants, people with disabilities, and people facing real gaps that systems do not currently reach may all need support at different moments.',now:'Happening now',nowTitle:'Care is already in motion.',nowLead:'Only approved public care actions appear here. Draft and internal activities stay off the public site.',care:'Care action',sharing:'Sharing action',detailPending:'Details are being prepared',view:'View activity →',status:'Current status',none:'No public activities right now',noneLead:'There are currently no active items that meet the public visibility rules. Drafts, internal activities and unapproved content remain private.',privacy:'Care ≠ exploiting vulnerability',privacyLead:'Participation is never exchanged for a person’s hardship, and protected cases are not required to become promotional material.',join:'I want to participate',joinTitle:'Join a current care action',joinLead:'Share your interest first; delivery follows each activity’s rules →',need:'I have a real need',needTitle:'Submit a gap that needs support',needLead:'Your story is not published. It first enters RCSCA’s internal review →',archive:'View past care actions →',noLabel:'Needs are not labels',noLabelTitle:'We look at the gap in this moment, not a permanent identity.',back:'Back to the Cycle of Goodness',backTitle:'Being supported does not define someone forever.',backLead:'When life becomes stable again, a person can re-enter the cycle in their own way. It is not repayment and does not need to be equal in value.',cycle:'Learn about the Cycle of Goodness →'},
'ja':{eyebrow:'ケア · 50%',hero:'支えが必要な姿は、一つではありません。',lead:'地方、児童養護、生活が厳しい家庭、ひとり親、高齢者、新住民、障害のある人、制度がまだ届かない実際の困りごとまで、必要な支えは時期によって変わります。',now:'現在進行中',nowTitle:'いま、実際に動いています。',nowLead:'承認され公開対象となった活動だけを表示します。下書きや内部活動は公開されません。',care:'ケア活動',sharing:'共有活動',detailPending:'詳細を整理中',view:'活動を見る →',status:'現在の状況',none:'現在、公開中の活動はありません',noneLead:'公開条件を満たす進行中の活動は現在ありません。下書き、内部活動、未承認内容は公開されません。',privacy:'ケア ≠ 弱さの消費',privacyLead:'困難な状況を参加の見返りにせず、保護対象の事例を広報素材にすることも求めません。',join:'参加したい',joinTitle:'現在のケア活動に参加する',joinLead:'まず参加意向を登録し、実施方法は各活動ルールに沿って案内します →',need:'実際の困りごとがある',needTitle:'支えが必要なギャップを伝える',needLead:'困りごとの物語は公開せず、まずRCSCA内部で確認します →',archive:'これまでのケア活動を見る →',noLabel:'ニーズはラベルではない',noLabelTitle:'見るのは今のギャップであり、その人に永久の属性を貼ることではありません。',back:'善の循環へ',backTitle:'支えられた経験が、その人を永久に定義するわけではありません。',backLead:'生活が安定した後、できる時に自分の方法で再び循環へ参加できます。返済でも等価交換でもありません。',cycle:'善の循環を知る →'},
'ko':{eyebrow:'돌봄 · 50%',hero:'도움이 필요한 모습은 하나가 아닙니다.',lead:'지역 공동체, 아동 보호 시설, 취약 가정, 한부모 가정, 고령자, 이주민, 장애인, 그리고 제도가 아직 닿지 못한 실제 공백까지 누구나 어느 순간 도움이 필요할 수 있습니다.',now:'진행 중',nowTitle:'지금 실제로 진행되고 있습니다.',nowLead:'승인되고 공개 가능한 공익 활동만 표시합니다. 초안과 내부 활동은 공개 사이트에 나오지 않습니다.',care:'돌봄 활동',sharing:'공유 활동',detailPending:'세부 내용 준비 중',view:'활동 보기 →',status:'현재 상태',none:'현재 공개 활동이 없습니다',noneLead:'현재 공개 조건을 충족하는 진행 중 활동이 없습니다. 초안, 내부 활동, 미승인 내용은 공개되지 않습니다.',privacy:'돌봄 ≠ 취약함의 소비',privacyLead:'어려운 상황을 참여의 대가로 사용하지 않으며 보호가 필요한 사례를 홍보 소재로 요구하지 않습니다.',join:'참여하고 싶어요',joinTitle:'현재 공익 활동에 참여하기',joinLead:'먼저 참여 의사를 남기고 실제 방식은 각 활동 규칙에 따라 안내합니다 →',need:'실제 도움이 필요해요',needTitle:'도움이 필요한 공백 제출',needLead:'사연을 공개하지 않고 먼저 RCSCA 내부 검토로 연결합니다 →',archive:'지난 돌봄 활동 보기 →',noLabel:'필요는 낙인이 아닙니다',noLabelTitle:'우리가 보는 것은 지금의 공백이지, 사람에게 영구적인 정체성을 붙이는 일이 아닙니다.',back:'선순환으로',backTitle:'도움을 받았다는 사실이 사람을 영원히 규정하지 않습니다.',backLead:'생활이 다시 안정되면 가능할 때 자신의 방식으로 선순환에 다시 참여할 수 있습니다. 갚아야 할 빚도, 같은 가치의 보답도 아닙니다.',cycle:'선순환 알아보기 →'}};
const tags:Record<Locale,string[]>={'zh-Hant':['偏鄉','育幼院','弱勢家庭','單親','年長','新住民','身障','制度接不到的真實缺口'],en:['Rural communities','Residential child care','Families under financial stress','Single-parent households','Older adults','New immigrants','Disability','Real gaps outside current systems'],ja:['地方','児童養護','生活が厳しい家庭','ひとり親','高齢者','新住民','障害','制度が届かない実際のギャップ'],ko:['지역 공동체','아동 보호 시설','취약 가정','한부모 가정','고령자','이주민','장애','제도가 닿지 못한 실제 공백']};
export default function CareClient({activities}:{activities:Activity[]}){const {locale}=useI18n();const c=copy[locale];return <main className="carePage"><SiteHeader/>
<section className="careHero"><div className="portalWrap"><div className="eyebrow">{c.eyebrow}</div><h1>{c.hero}</h1><p>{c.lead}</p></div></section>
<section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">{c.now}</div><h2>{c.nowTitle}</h2></div><p>{c.nowLead}</p></div>{activities.length?<div className="portalGrid three">{activities.map(a=><article key={a.id}><small>{a.category==='care'?c.care:c.sharing}</small><h3>{a.name}</h3><p>{a.public_summary||c.detailPending}</p><a className="networkCta" href={`/care-actions/activity/${a.id}`}>{c.view}</a></article>)}</div>:<div className="careFeature"><div><small>{c.status}</small><h3>{c.none}</h3><p>{c.noneLead}</p></div><aside><strong>{c.privacy}</strong><p>{c.privacyLead}</p></aside></div>}</div></section>
<section className="careTwoDoors"><div className="portalWrap"><a href="/care-actions/participate"><small>{c.join}</small><b>{c.joinTitle}</b><span>{c.joinLead}</span></a><a href="/care-actions/request"><small>{c.need}</small><b>{c.needTitle}</b><span>{c.needLead}</span></a><a className="bigTextLink" href="/care-actions/archive">{c.archive}</a></div></section>
<section className="portalSection softPortal compactCareTags"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">{c.noLabel}</div><h2>{c.noLabelTitle}</h2></div></div><div className="careTags">{tags[locale].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="portalSection darkPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">{c.back}</div><h2>{c.backTitle}</h2></div><p>{c.backLead}</p></div><a className="bigTextLink" href="/cycle-of-goodness">{c.cycle}</a></div></section></main>}
