import SiteHeader from '../SiteHeader';
import { publicSelect } from '../../lib/supabase-public';
type Activity={id:string;code:string;name:string;category:string;status:string;public_summary:string|null;starts_at:string|null;ends_at:string|null};
export const dynamic='force-dynamic';
export default async function Care(){const activities=await publicSelect<Activity>('activities','select=id,code,name,category,status,public_summary,starts_at,ends_at&status=in.(published,active,completed)&order=starts_at.desc.nullslast');return <main className="carePage"><SiteHeader/>
<section className="careHero"><div className="portalWrap"><div className="eyebrow">關懷 · 50%</div><h1>需要被看見的，不只有一種樣子。</h1><p>偏鄉、育幼院、弱勢家庭、單親、年長、新住民、身障，以及制度暫時接不到但確有真實缺口的人，都可能在某個時間需要被接住。</p></div></section>
<section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">現在進行中</div><h2>現在正在發生。</h2></div><p>正式公開的公益行動會直接由資料庫帶入；草稿與內部測試活動不會出現在公開網站。</p></div>{activities.length?<div className="portalGrid three">{activities.map(a=><article key={a.id}><small>{a.category==='care'?'關懷行動':'共享行動'}</small><h3>{a.name}</h3><p>{a.public_summary||'詳細內容整理中'}</p><a className="networkCta" href="/care-actions/participate">登記參與 →</a></article>)}</div>:<div className="careFeature"><div><small>目前狀態</small><h3>尚無正式公開中的活動</h3><p>Staging 目前只有草稿測試資料，因此依 RLS 規則不會對一般訪客顯示。這代表公開／內部資料邊界正在正常運作。</p></div><aside><strong>關懷 ≠ 消費弱勢</strong><p>不以弱勢處境換取參與，不要求特殊保護個案成為宣傳素材。</p></aside></div>}</div></section>
<section className="careTwoDoors"><div className="portalWrap"><a href="/care-actions/participate"><small>我想參與</small><b>加入目前的公益行動</b><span>先留下參與意願，交付方式可依活動規則處理 →</span></a><a href="/care-actions/request"><small>我有真實需求</small><b>提出需要被接住的缺口</b><span>不公開求助故事，先進入 RCSCA 內部評估 →</span></a><a className="bigTextLink" href="/care-actions/archive">查看歷年關懷行動 →</a></div></section>
<section className="portalSection softPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">我們關懷的對象</div><h2>服務對象不是標籤，而是此刻的需求狀態。</h2></div></div><div className="careTags">{['偏鄉','育幼院','弱勢家庭','單親','年長','新住民','身障','制度接不到的真實缺口'].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="portalSection darkPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">回到善循環</div><h2>被接住，不代表被永久定義。</h2></div><p>當生活重新站穩，有能力時，可以用自己的方式再次進入善循環；不是還債，也不要求等值。</p></div><a className="bigTextLink" href="/cycle-of-goodness">了解善循環 →</a></div></section></main>}
