'use client';
import {useEffect,useMemo,useState} from 'react';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';
import {Locale,useI18n} from '../../i18n';
type Foot={id:string;created_at:string;footprint_type:string;description:string|null;source_type:string};
type Part={id:string;status:string;created_at:string;participation_type:string;activities:{name:string}|null};
const copy:Record<Locale,any>={
 'zh-Hant':{loading:'正在讀取共享足跡…',guest:'登入後查看自己的共享足跡。',guestLead:'一般參觀者不會看到任何個人紀錄。',login:'前往登入 →',cancelFail:'目前無法取消；已核實或已進入處理的登記不能自行移除。',cancelDone:'已取消尚未核實的參與登記。',progress:'公益參與進度',progressTitle:'登記與完成核實是兩件事。',progressLead:'尚未核實的登記可以自行取消；核實後才會形成共享足跡。',pending:'待核實',verified:'已核實',rejected:'未核實',activity:'公益活動',cancel:'取消登記',footprint:'共享足跡',completed:'已完成並被記錄',care:'關懷',careLead:'公益行動與服務',connection:'連結',connectionLead:'媒合、資源與人脈',sharedConnection:'共享連結',careType:'公益關懷',done:'已完成一筆共享',latest:'最新',recorded:'已記錄',empty:'目前還沒有已核實的共享足跡。',emptyLead:'完成公益參與或其他經核實的共享後，紀錄會出現在這裡。'},
 en:{loading:'Loading sharing footprints…',guest:'Sign in to view your sharing footprints.',guestLead:'Visitors cannot see any personal records.',login:'Go to sign in →',cancelFail:'This registration cannot be cancelled. Verified or processing records cannot be removed by the user.',cancelDone:'The unverified participation registration was cancelled.',progress:'Participation progress',progressTitle:'Registration and verification are separate steps.',progressLead:'You can cancel an unverified registration. A sharing footprint is created only after verification.',pending:'Pending verification',verified:'Verified',rejected:'Not verified',activity:'Community activity',cancel:'Cancel registration',footprint:'Sharing footprints',completed:'Completed and recorded',care:'Care',careLead:'Community action and service',connection:'Connections',connectionLead:'Matches, resources and people',sharedConnection:'Shared connections',careType:'Community care',done:'A sharing action was completed',latest:'Latest',recorded:'Recorded',empty:'No verified sharing footprints yet.',emptyLead:'Verified community participation and other sharing records will appear here.'},
 ja:{loading:'共有の足跡を読み込み中…',guest:'ログインすると自分の共有の足跡を確認できます。',guestLead:'一般の閲覧者に個人記録は表示されません。',login:'ログインへ →',cancelFail:'現在キャンセルできません。確認済みまたは処理中の登録は本人が削除できません。',cancelDone:'未確認の参加登録をキャンセルしました。',progress:'公益参加の進捗',progressTitle:'登録と確認完了は別の段階です。',progressLead:'未確認の登録はキャンセルできます。確認後に共有の足跡として記録されます。',pending:'確認待ち',verified:'確認済み',rejected:'未確認',activity:'公益活動',cancel:'登録をキャンセル',footprint:'共有の足跡',completed:'完了・記録済み',care:'ケア',careLead:'公益活動とサービス',connection:'つながり',connectionLead:'マッチング、資源、人のつながり',sharedConnection:'共有のつながり',careType:'公益ケア',done:'共有を1件完了しました',latest:'最新',recorded:'記録済み',empty:'確認済みの共有の足跡はまだありません。',emptyLead:'公益参加などの共有が確認されると、ここに記録されます。'},
 ko:{loading:'공유 발자취를 불러오는 중…',guest:'로그인 후 나의 공유 발자취를 확인하세요.',guestLead:'일반 방문자에게는 개인 기록이 표시되지 않습니다.',login:'로그인으로 →',cancelFail:'현재 취소할 수 없습니다. 확인 완료 또는 처리 중인 등록은 직접 삭제할 수 없습니다.',cancelDone:'확인 전 참여 등록을 취소했습니다.',progress:'공익 참여 진행',progressTitle:'등록과 확인 완료는 서로 다른 단계입니다.',progressLead:'확인 전 등록은 취소할 수 있으며, 확인 후 공유 발자취로 기록됩니다.',pending:'확인 대기',verified:'확인 완료',rejected:'확인되지 않음',activity:'공익 활동',cancel:'등록 취소',footprint:'공유 발자취',completed:'완료 및 기록됨',care:'돌봄',careLead:'공익 활동과 서비스',connection:'연결',connectionLead:'매칭, 자원 및 인맥',sharedConnection:'공유 연결',careType:'공익 돌봄',done:'공유 활동 1건 완료',latest:'최신',recorded:'기록됨',empty:'아직 확인 완료된 공유 발자취가 없습니다.',emptyLead:'공익 참여나 기타 공유가 확인되면 여기에 기록됩니다.'}
};
const dateLocale:Record<Locale,string>={'zh-Hant':'zh-TW',en:'en-US',ja:'ja-JP',ko:'ko-KR'};
export default function LiveActivity(){
 const {locale}=useI18n();const c=copy[locale];
 const [loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[rows,setRows]=useState<Foot[]>([]),[parts,setParts]=useState<Part[]>([]),[notice,setNotice]=useState('');
 async function load(){const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session){setLoading(false);return;}setSignedIn(true);const [f,p]=await Promise.all([s.from('sharing_footprints').select('id,created_at,footprint_type,description,source_type').eq('user_id',session.user.id).order('created_at',{ascending:false}),s.from('activity_participations').select('id,status,created_at,participation_type,activities(name)').eq('user_id',session.user.id).order('created_at',{ascending:false})]);setRows((f.data||[]) as Foot[]);setParts((p.data||[]) as any);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function cancel(id:string){const s=getSupabaseBrowserClient();const {error}=await s.rpc('cancel_my_activity_participation',{p_participation_id:id});if(error){setNotice(c.cancelFail);return;}setNotice(c.cancelDone);load()}
 const summary=useMemo(()=>({all:rows.length,care:rows.filter(x=>x.footprint_type==='care').length,connection:rows.filter(x=>x.footprint_type==='connection').length}),[rows]);
 if(loading)return <p>{c.loading}</p>;
 if(!signedIn)return <div className="privacyCallout"><strong>{c.guest}</strong><p>{c.guestLead}</p><a href="/login">{c.login}</a></div>;
 const status=(value:string)=>value==='pending'?c.pending:value==='verified'?c.verified:c.rejected;
 return <>{notice&&<div className="workflowNotice">{notice}</div>}{parts.length>0&&<section className="esgAssetPanel"><div className="sectionHead"><div><div className="eyebrow">{c.progress}</div><h2>{c.progressTitle}</h2></div><p>{c.progressLead}</p></div><div className="assetGrid">{parts.slice(0,8).map(p=><article key={p.id}><small>{status(p.status)}</small><h3>{p.activities?.name||c.activity}</h3><p>{new Date(p.created_at).toLocaleDateString(dateLocale[locale])}</p>{p.status==='pending'&&<button className="secondaryAction" onClick={()=>cancel(p.id)}>{c.cancel}</button>}</article>)}</div></section>}
 {rows.length?<><div className="footprintSummary"><article><small>{c.footprint}</small><strong>{summary.all}</strong><span>{c.completed}</span></article><article><small>{c.care}</small><strong>{summary.care}</strong><span>{c.careLead}</span></article><article><small>{c.connection}</small><strong>{summary.connection}</strong><span>{c.connectionLead}</span></article></div><div className="footprintBalance"><div><span>{c.care}</span><b style={{width:`${summary.all?Math.max(8,summary.care/summary.all*100):0}%`}}/></div><div><span>{c.sharedConnection}</span><b style={{width:`${summary.all?Math.max(8,summary.connection/summary.all*100):0}%`}}/></div></div><div className="activityTimeline">{rows.map((r,i)=><article key={r.id}><time>{new Date(r.created_at).toLocaleDateString(dateLocale[locale])}</time><div><small>{r.footprint_type==='care'?c.careType:c.sharedConnection}</small><h3>{r.description||c.done}</h3><p>{r.source_type}</p></div><span>{i===0?c.latest:c.recorded}</span></article>)}</div></>:<div className="privacyCallout"><strong>{c.empty}</strong><p>{c.emptyLead}</p></div>}</>;
}
