'use client';
import SiteHeader from '../../SiteHeader';import {FormEvent,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';import {networkCopy} from '../../networkCopy';
const flow:Record<Locale,any>={
 'zh-Hant':{signin:'請先登入，再送出媒合需求。',member:'這項深層媒合功能限 RCSCA MEMBER 使用。',fail:'送出失敗，請稍後再試。',done:'已送出。你可以到「我的需求與進度」查看目前狀態。',title:'共享媒合需求',region:'地區',category:'類別',options:['水電／工程','室內設計','法律','保險','會計','照護','汽車','工作／人才','其他']},
 en:{signin:'Please sign in before submitting a matching request.',member:'This deeper matching feature is available to RCSCA MEMBER accounts only.',fail:'Submission failed. Please try again later.',done:'Submitted. View the current status under My Requests & Progress.',title:'Sharing match request',region:'Region',category:'Category',options:['Plumbing / engineering','Interior design','Legal','Insurance','Accounting','Care','Automotive','Jobs / talent','Other']},
 ja:{signin:'ログインしてからマッチング依頼を送信してください。',member:'この深層マッチング機能はRCSCA MEMBER限定です。',fail:'送信できませんでした。後ほど再度お試しください。',done:'送信しました。「依頼と進捗」で現在の状況を確認できます。',title:'共有マッチング依頼',region:'地域',category:'カテゴリー',options:['水道／工事','インテリアデザイン','法律','保険','会計','ケア','自動車','仕事／人材','その他']},
 ko:{signin:'로그인 후 매칭 요청을 제출해 주세요.',member:'이 심화 매칭 기능은 RCSCA MEMBER만 사용할 수 있습니다.',fail:'제출하지 못했습니다. 잠시 후 다시 시도해 주세요.',done:'제출했습니다. 나의 요청 및 진행에서 현재 상태를 확인할 수 있습니다.',title:'공유 매칭 요청',region:'지역',category:'분류',options:['설비／공사','인테리어 디자인','법률','보험','회계','돌봄','자동차','일자리／인재','기타']}
};
export default function MemberRequest(){const{locale}=useI18n(),c=networkCopy[locale],f=flow[locale];const[category,setCategory]=useState(''),[region,setRegion]=useState(''),[detail,setDetail]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false);async function submit(e:FormEvent){e.preventDefault();setSending(true);setMessage('');try{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session){setMessage(f.signin);return}const title=category?`${category}${region?`｜${region}`:''}`:f.title;const{error}=await s.rpc('member_submit_network_request',{p_request_kind:'life',p_title:title,p_public_summary:detail.slice(0,120),p_private_detail:`${f.region}：${region}\n${f.category}：${category}\n${detail}`,p_requester_enterprise_id:undefined});if(error){setMessage(error.message.includes('active_membership_required')?f.member:f.fail);return}setMessage(f.done);setCategory('');setRegion('');setDetail('')}finally{setSending(false)}}return <main className="flowPage"><SiteHeader/><section className="flowHero"><div className="portalWrap"><div className="eyebrow">{c.lifeEye}</div><h1>{c.lifeTitle}</h1><p>{c.lifeLead}</p></div></section><section className="portalSection"><div className="portalWrap actionForm"><form onSubmit={submit}><div className="briefFields"><label><span className="srOnly">{c.category}</span><select required value={category} onChange={e=>setCategory(e.target.value)}><option value="">{c.category}</option>{f.options.map((x:string)=><option key={x}>{x}</option>)}</select></label><label><span className="srOnly">{c.region}</span><input required placeholder={c.region} value={region} onChange={e=>setRegion(e.target.value)}/></label><label><span className="srOnly">{c.detail}</span><textarea required placeholder={c.detail} value={detail} onChange={e=>setDetail(e.target.value)}/></label></div><button className="submitLead" disabled={sending}>{sending?c.sending:c.submitLife}</button>{message&&<div className="authMessage sent" role="status" aria-live="polite">{message}</div>}</form><aside><b>{c.private}</b><p>{c.privateDesc}</p><b>{c.consent}</b><p>{c.consentDesc}</p></aside></div></section></main>}
