import BrandEntrance from './BrandEntrance';
import MusicController from './MusicController';
import LanguageSwitcher from './LanguageSwitcher';

const OneMark=({className=''})=><span className={`oneMark ${className}`}><b>1</b><i>%</i></span>;

export default function Home(){return <><BrandEntrance/><MusicController/><main>
<header className="nav"><div className="navInner">
<a className="brandLockup" href="#top" aria-label="回到 RCSCA 首頁"><span className="brandStack"><span className="brandRcsca">RCSCA</span><small>Cycle of Goodness</small></span><span className="brandCross">×</span><OneMark className="brandOne"/></a>
<nav><a href="/my-1percent">MY 1%</a><a href="/1percent-partner">1% PARTNER</a><a href="/care-actions">公益行動</a><a href="/1percent-network">1% NETWORK</a><a href="/cycle-of-goodness">CYCLE OF GOODNESS</a><LanguageSwitcher/><a className="pill" href="/prototypes/RCSCA_MY1percent_signup_flow.html">登入／加入</a></nav>
</div></header>

<section id="top" className="hero homeHero"><div className="heroInner"><div className="eyebrow">RCSCA · CYCLE OF GOODNESS × 1%</div><h1>每個人的 <OneMark className="heroOne"/>，都不一樣。</h1><p>共享關懷不只關於付出，也關於連結。個人與企業，都能用自己的方式進入同一個循環。</p><div className="heroActions"><a className="primary" href="#gateway">找到我的入口</a><a className="textLink" href="/cycle-of-goodness">什麼是善循環？ →</a></div></div>
<div className="livingCycle" aria-label="Cycle of Goodness 動態循環"><div className="cycleGlow"></div><div className="cycleCenter"><span>RCSCA</span><small>Cycle of Goodness</small></div><span className="flowNode n1">PERSON</span><span className="flowNode n2">CARE</span><span className="flowNode n3">PARTNER</span><span className="flowNode n4">CONNECT</span><div className="orbit o1"></div><div className="orbit o2"></div><div className="flowDot d1"></div><div className="flowDot d2"></div><div className="flowDot d3"></div><div className="cycleOne"><OneMark/></div><small className="cycleCaption">PEOPLE × PARTNERS × CARE × CONNECT</small></div></section>

<section id="cycle" className="cycleExplain"><div className="section cycleExplainInner"><div className="sectionHead"><div><div className="eyebrow">CYCLE OF GOODNESS</div><h2>善循環，不是誰一直幫助誰。</h2></div><p>每個人都有可以分享的 1%，也可能有需要被接住的時候。角色會改變，資源會流動，新的 1% 會再次出現。</p></div><div className="cycleSteps"><div><i>01</i><b>分享 1%</b><span>個人或企業，以自己的方式加入。</span></div><em>→</em><div><i>02</i><b>被連結</b><span>需求、專業、資源與人找到彼此。</span></div><em>→</em><div><i>03</i><b>有人被接住</b><span>不是被貼上永久的受助標籤。</span></div><em>→</em><div><i>04</i><b>角色改變</b><span>有能力時，也能成為新的共享者。</span></div><em>→</em><div><i>05</i><b>新的 1%</b><span>再次進入下一段關係。</span></div></div><p className="cycleStatement">當一個人的 1%，成為下一個人的開始，<b>Cycle of Goodness</b> 就發生了。</p></div></section>

<section id="gateway" className="gateway"><div className="section"><div className="sectionHead"><div><div className="eyebrow">TWO EQUAL ROLES</div><h2>個人與企業，各自走進同一個 Cycle。</h2></div><p>兩邊同等重要。首頁只提供入口，完整身份、等級、權限與工具回到各自的專區。</p></div><div className="gatewayGrid"><a className="gatewayCard person" href="/my-1percent"><small>PERSON · MY 1%</small><strong>個人</strong><p>我的參與、共享足跡、Level、數位共享卡、小隊、會員身份與專屬權限。</p><span>進入 MY 1% →</span></a><a id="partner" className="gatewayCard partner" href="/1percent-partner"><small>ENTERPRISE · 1% PARTNER</small><strong>企業夥伴</strong><p>企業的 1%、共享紀錄、Impact、年度標章、工作機會與 Network 連結。</p><span>進入 1% PARTNER →</span></a></div></div></section>

<section className="twoMissions"><div className="section"><div className="sectionHead"><div><div className="eyebrow">CARE × CONNECT</div><h2>共享一半，關懷一半。</h2></div><p>公益關懷與人脈資源連結同等重要；兩者交會，才是「共享關懷」。</p></div><div className="missionGrid"><article id="care"><small>CARE · 50%</small><h3>公益關懷</h3><p>當孩子、家庭、個人或制度接不到的需求出現，讓真實需要被看見、被評估、被接住。</p><a href="#now">看正在發生的公益行動 →</a></article><article id="network"><small>CONNECT · 50%</small><h3>1% NETWORK</h3><p>讓專業、企業、店家、工作、人才、服務與 Connection 找到彼此，也看見網絡還缺哪一塊。</p><a href="#networkPreview">探索 1% Network →</a></article></div></div></section>

<section id="now" className="nowBand"><div className="nowInner"><div><div className="eyebrow">HAPPENING NOW · CARE</div><h2>2026 中秋物資認購</h2><p>育幼院／弱勢家庭中秋禮盒、生活及清潔物資。認購最低需求 200 單位，持續增加中。</p></div><a href="#">查看目前行動 →</a></div></section>

<section id="networkPreview" className="networkSection"><div className="section networkInner"><div className="sectionHead"><div><div className="eyebrow">1% NETWORK · CONNECT</div><h2>看見已經連上的，也看見還缺的。</h2></div><p>首頁只預覽網絡狀態；完整產業、區域、企業／店家與會員權限資訊放在 1% Network 專區。</p></div><div className="networkPreviewGrid"><div className="miniNetwork"><div className="networkCore"><span>RCSCA</span><OneMark/><small>NETWORK</small></div><div className="miniNode mn1"><b>室內設計</b><span>3 PARTNERS</span></div><div className="miniNode mn2"><b>餐飲</b><span>8 PARTNERS</span></div><div className="miniNode mn3 scarce"><b>法律</b><span>1 · 稀缺</span></div><div className="miniNode mn4 empty"><b>交通運輸</b><span>等待第一個 1%</span></div><div className="miniNode mn5"><b>旅宿</b><span>4 PARTNERS</span></div><div className="miniNode mn6 empty"><b>寵物服務</b><span>等待加入</span></div><div className="networkPulse p1"></div><div className="networkPulse p2"></div></div><div className="networkInfo"><div className="networkStatus"><span>12</span><p>示意產業節點 <b>實際資料上線後動態計算</b></p></div><h3>成為這個產業的第一個 1%。</h3><p>產業節點會直接顯示目前加入的企業／店家數；稀缺與尚缺類別保留可見，讓新的夥伴知道自己的專業可以補上哪一塊。</p><p className="microNote">不販售獨家席位、不限制一個產業只能一家。完整頁面可再依區域查看缺口。</p><a className="primary" href="/1percent-network">進入 1% NETWORK</a></div></div></div></section>

<section id="impact" className="impact"><div className="impactInner"><div className="eyebrow">SHARED FOOTPRINT</div><h2>已經發生的關懷，持續累積。</h2><div className="stats"><div><strong>4,197+</strong><span>偏鄉育幼院服務人次 持續增加中</span></div><div><strong>1,273+</strong><span>弱勢家庭服務戶次 持續增加中</span></div><div><strong>2018 →</strong><span>從這一年開始 持續走下去</span></div></div></div></section>

<section className="rootsStory" aria-label="第一個十年到下一個十年的品牌故事"><div className="rootsSky"><div className="rootsCopy"><div className="eyebrow">THE FIRST TEN YEARS → THE NEXT TEN YEARS</div><h2>第一個十年， 我們用行動落實了關懷。</h2><p>有些事，不被看見，也一直在發生。那些沒有被放大的行動、沒有被消費的故事，一點一點向下扎根，成為第一個十年最真實的累積。</p></div><div className="sprout"><span className="sproutLeaf leafLeft"></span><span className="sproutLeaf leafRight"></span><span className="sproutStem"></span><span className="sproutMark"><OneMark/></span></div></div><div className="soilLine"></div><div className="rootsGround"><div className="rootGlow"></div><div className="rootSystem"><span className="root trunk"></span><span className="root r1"></span><span className="root r2"></span><span className="root r3"></span><span className="root r4"></span><span className="root r5"></span><span className="root r6"></span><span className="root r7"></span><span className="root r8"></span></div><div className="rootWords"><span>陪伴</span><span>孩子</span><span>家庭</span><span>物資</span><span>教育</span><span>偏鄉</span><span>單親</span><span>年長</span><span>新住民</span><span>身障</span><span>行動</span><span>連結</span></div><div className="groundCopy"><small>十年扎根 · LOW PROFILE, REAL ACTION</small><h3>下一個十年， 讓共享真正從這裡發芽。</h3><p><b>第一個十年，我們落實關懷；下一個十年，我們透過 1% 的機制，讓個人、企業、需求與資源彼此連結，讓「共享」真正成為日常。</b></p><p className="rootsTagline">從關懷扎根，到共享發芽。這不是重新開始，而是讓十年的累積進入下一個 Cycle。</p><div className="rootsSignature"><span className="brandStack"><span className="brandRcsca">RCSCA</span><small>Cycle of Goodness</small></span><span>×</span><OneMark/></div></div></div></section>

<section className="join"><div className="eyebrow">ENTER THE CYCLE</div><h2>你的 1%，可以從任何位置開始。</h2><p>先選擇你的角色；完整制度與功能，在個人與企業專區裡一目瞭然。</p><div className="joinActions"><a className="primary light" href="/my-1percent">MY 1%</a><a className="outlineLight" href="/1percent-partner">1% PARTNER</a></div></section>
<footer><a className="footerBrand" href="#top"><span className="brandStack"><span className="brandRcsca">RCSCA</span><small>Cycle of Goodness</small></span><span>×</span><OneMark/></a><p>© RCSCA · Cycle of Goodness</p></footer>
</main></>}
