'use client';
import BrandEntrance from './BrandEntrance';
import SiteHeader from './SiteHeader';
import {useI18n} from './i18n';

const OneMark=({className=''})=><span className={`oneMark ${className}`}><b>1</b><i>%</i></span>;

export default function Home(){const {t}=useI18n();return <><BrandEntrance/><main>
<SiteHeader/>
<section id="top" className="hero homeHero"><div className="heroInner"><div className="eyebrow">RCSCA · CYCLE OF GOODNESS × 1%</div><h1>{t('home.title').split('1%')[0]}<OneMark className="heroOne"/>{t('home.title').split('1%')[1]||''}</h1><p>{t('home.lead')}</p><div className="heroActions"><a className="primary" href="#gateway">{t('home.find')}</a><a className="textLink" href="/cycle-of-goodness">{t('home.what')}</a></div></div>
<div className="livingCycle" aria-label="Cycle of Goodness"><div className="cycleGlow"></div><div className="cycleCenter"><span>RCSCA</span><small>Cycle of Goodness</small></div><span className="flowNode n1">{t('home.personNode')}</span><span className="flowNode n2">{t('home.careNode')}</span><span className="flowNode n3">{t('home.businessNode')}</span><span className="flowNode n4">{t('home.connectNode')}</span><div className="orbit o1"></div><div className="orbit o2"></div><div className="flowDot d1"></div><div className="flowDot d2"></div><div className="flowDot d3"></div><div className="cycleOne"><OneMark/></div><small className="cycleCaption">{t('home.cycleCaption')}</small></div></section>

<section className="routeGuide" aria-label="快速找到入口"><div className="routeGuideInner"><div className="routeGuideIntro"><small>{t('home.first')}</small><strong>{t('home.start')}</strong></div><a href="/care-actions"><em>{t('home.care')}</em><b>{t('home.careGo')}</b><span>{t('home.careDesc')}</span></a><a href="/1percent-network"><em>{t('home.network')}</em><b>{t('home.networkGo')}</b><span>{t('home.networkDesc')}</span></a><a href="/my-1percent"><em>{t('home.person')}</em><b>{t('home.personGo')}</b><span>{t('home.personDesc')}</span></a><a href="/1percent-partner"><em>{t('home.business')}</em><b>{t('home.businessGo')}</b><span>{t('home.businessDesc')}</span></a></div></section>

<section id="gateway" className="gateway compactGateway"><div className="section"><div className="sectionHead"><div><div className="eyebrow">{t('home.gatewayEye')}</div><h2>{t('home.gatewayTitle')}</h2></div><p>{t('home.gatewayLead')}</p></div><div className="gatewayGrid threeGateway"><a className="gatewayCard person" href="/my-1percent"><small>個人 · MY 1%</small><strong>留下我的共享足跡</strong><p>參與、共享、連結與自己的 1%。</p><span>{t('home.personGo')} →</span></a><a className="gatewayCard partner" href="/1percent-partner"><small>企業 · 1% PARTNER</small><strong>{t('home.businessGo')}</strong><p>從需求設計、執行媒合到成果整理。</p><span>進入企業專區 →</span></a><a className="gatewayCard network" href="/1percent-network"><small>連結 · 1% NETWORK</small><strong>找人、找專業、找資源</strong><p>看已連上的節點，也看目前還缺哪一塊。</p><span>{t('home.networkGo')} →</span></a></div><div className="gatewayFoot"><a href="/cycle-of-goodness">先理解 Cycle of Goodness →</a><a href="/care-actions">查看正在發生的公益行動 →</a></div></div></section>

<section id="now" className="nowBand"><div className="nowInner"><div><div className="eyebrow">現在進行中 · 公益關懷</div><h2>2026 中秋物資認購</h2><p>育幼院／弱勢家庭中秋禮盒、生活及清潔物資。認購最低需求 200 單位，持續增加中。</p></div><a href="/care-actions">查看目前行動 →</a></div></section>

<section id="networkPreview" className="networkSection"><div className="section networkInner"><div className="sectionHead"><div><div className="eyebrow">1% NETWORK · 共享連結</div><h2>看見已經連上的，也看見還缺的。</h2></div><p>首頁只看一眼網絡缺口；完整產業、區域與夥伴資訊到 1% NETWORK 查看。</p></div><div className="networkPreviewGrid"><div className="miniNetwork"><div className="networkCore"><span>RCSCA</span><OneMark/><small>共享網絡</small></div><div className="miniNode mn1"><b>室內設計</b><span>專業節點</span></div><div className="miniNode mn2"><b>餐飲</b><span>生活節點</span></div><div className="miniNode mn3 scarce"><b>法律</b><span>專業節點</span></div><div className="miniNode mn4 empty"><b>交通運輸</b><span>等待更多連結</span></div><div className="miniNode mn5"><b>旅宿</b><span>生活節點</span></div><div className="miniNode mn6 empty"><b>寵物服務</b><span>等待更多連結</span></div><div className="networkPulse p1"></div><div className="networkPulse p2"></div></div><div className="networkInfo"><h3>成為這個產業的第一個 1%。</h3><p>完整 Network 會依已核准公開資料呈現實際節點與缺口；首頁只用概念圖快速說明「已連結」與「仍待補上」的關係。</p><p className="microNote">不販售獨家席位，也不限制一個產業只能一家。</p><a className="primary" href="/1percent-network">進入 1% NETWORK</a></div></div></div></section>

<section id="impact" className="impact"><div className="impactInner"><div className="eyebrow">{t('home.footprint')}</div><h2>已經發生的關懷，持續累積。</h2><div className="stats"><div><strong>4,197+</strong><span>偏鄉育幼院服務人次 持續增加中</span></div><div><strong>1,273+</strong><span>弱勢家庭服務戶次 持續增加中</span></div><div><strong>2018 →</strong><span>從這一年開始 持續走下去</span></div></div></div></section>

<section className="rootsStory" aria-label="第一個十年到下一個十年的品牌故事"><div className="rootsSky"><div className="rootsCopy"><div className="eyebrow">第一個十年 → 下一個十年</div><h2>第一個十年， 我們用行動落實了關懷。</h2><p>有些事，不被看見，也一直在發生。那些沒有被放大的行動、沒有被消費的故事，一點一點向下扎根，成為第一個十年最真實的累積。</p></div><div className="sprout"><span className="sproutLeaf leafLeft"></span><span className="sproutLeaf leafRight"></span><span className="sproutStem"></span><span className="sproutMark"><OneMark/></span></div></div><div className="soilLine"></div><div className="rootsGround"><div className="rootGlow"></div><div className="rootSystem"><span className="root trunk"></span><span className="root r1"></span><span className="root r2"></span><span className="root r3"></span><span className="root r4"></span><span className="root r5"></span><span className="root r6"></span><span className="root r7"></span><span className="root r8"></span></div><div className="rootWords"><span>陪伴</span><span>孩子</span><span>家庭</span><span>物資</span><span>教育</span><span>偏鄉</span><span>單親</span><span>年長</span><span>新住民</span><span>身障</span><span>行動</span><span>連結</span></div><div className="groundCopy"><small>十年扎根 · 低調，但一直在做</small><h3>下一個十年， 讓共享真正從這裡發芽。</h3><p><b>第一個十年，我們讓關懷落地；下一個十年，我們要讓每一份 1% 彼此連結，讓共享成為可以持續發生的日常。</b></p><p className="rootsTagline">關懷是根，共享是下一段生長。十年的累積不是終點，而是讓更多人彼此成為下一個開始。</p><div className="rootsSignature"><span className="brandStack"><span className="brandRcsca">RCSCA</span><small>Cycle of Goodness</small></span><span>×</span><OneMark/></div></div></div></section>

<section className="join"><div className="eyebrow">{t('home.joinEye')}</div><h2>{t('home.joinTitle')}</h2><p>{t('home.joinLead')}</p><div className="joinActions"><a className="primary light" href="/my-1percent">MY 1%</a><a className="outlineLight" href="/1percent-partner">1% PARTNER</a></div></section>

</main></>}
