'use client';
import SiteHeader from '../../SiteHeader';
import {useState} from 'react';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';
import {Locale,useI18n} from '../../i18n';
const optionValues=['資金／物資','產品／服務','專業能力','員工人力','工作機會','場地','人脈連結','尚未確定'] as const;
const directionKeys=['care','connection','esg','consult'] as const;
const copy:Record<Locale,any>={
 'zh-Hant':{options:['資金／物資','產品／服務','專業能力','員工人力','工作機會','場地','人脈連結','尚未確定'],directions:[['公益關懷','參與真實需求、公益專案或員工行動。'],['資源連結','工作、人才、專業、服務與 1% Network。'],['ESG 專案','由企業目標出發，規劃可落地的合作與成果。'],['先聊聊','還不知道最適合哪一條路，先由 RCSCA 協助判斷。']],signin:'請先登入，再送出企業加入申請。',required:'請先完成企業名稱、統編、聯絡人與 Email。',failed:'目前無法送出，請稍後再試。',sent:'申請已正式送出。案件識別：',eye:'1% 企業共享夥伴 · 加入流程',hero:'先讓我們知道，企業可以從哪一個 1% 開始。',lead:'加入不以贊助金額為門檻。企業可以從產品、專業、工作機會、人力、場地或一個人脈連結開始。',steps:['企業身份','可分享的 1%','合作方向','送出審核'],basic:'企業基本資料',company:'企業／店家名稱',taxId:'統一編號',contact:'聯絡人',phone:'電話',region:'所在縣市',share:'企業目前可能分享的 1%',multi:'可以複選，也可以先選「尚未確定」。',start:'企業目前比較想從哪裡開始？',after:'送出後會發生什麼？',timeline:['RCSCA 檢查企業身份與需求','確認適合的共享／合作路徑','完成第一筆真實共享後，建立年度共享紀錄','符合條件後取得年度 1% 標章'],sending:'送出中…',submit:'送出加入申請 →',previous:'← 上一步',next:'下一步 →'},
 'en':{options:['Funding / goods','Products / services','Professional expertise','Employee participation','Job opportunities','Space','Network connections','Not sure yet'],directions:[['Community care','Take part in real needs, public-benefit projects, or employee actions.'],['Resource connections','Jobs, talent, expertise, services, and the 1% Network.'],['ESG project','Start from enterprise goals and plan practical collaboration and outcomes.'],['Talk first','If the best path is unclear, let RCSCA help assess it.']],signin:'Sign in before submitting an enterprise application.',required:'Complete the enterprise name, tax ID, contact person, and email.',failed:'Unable to submit right now. Please try again later.',sent:'Application submitted. Case ID: ',eye:'1% Enterprise Partner · Application',hero:'Tell us where your enterprise can begin with its 1%.',lead:'There is no sponsorship threshold. Start with a product, expertise, job opportunity, people, space, or one useful connection.',steps:['Enterprise identity','Shareable 1%','Collaboration path','Submit for review'],basic:'Enterprise details',company:'Enterprise / shop name',taxId:'Tax ID',contact:'Contact person',phone:'Phone',region:'City or region',share:'What the enterprise may be able to share',multi:'Choose more than one, or select “Not sure yet.”',start:'Where would the enterprise prefer to begin?',after:'What happens after submission?',timeline:['RCSCA reviews enterprise identity and needs','Confirm the appropriate sharing or collaboration path','Create an annual sharing record after the first verified contribution','Receive the annual 1% badge after meeting its criteria'],sending:'Submitting…',submit:'Submit application →',previous:'← Previous',next:'Next →'},
 'ja':{options:['資金／物資','製品／サービス','専門能力','従業員参加','仕事の機会','場所','人脈のつながり','未定'],directions:[['公益ケア','実際のニーズ、公益プロジェクト、従業員活動に参加。'],['資源連携','仕事、人材、専門性、サービス、1% Network。'],['ESGプロジェクト','企業目標から、実行可能な連携と成果を計画。'],['まず相談','最適な道がまだ分からない場合、RCSCAが判断を支援。']],signin:'ログインしてから企業参加申請を送信してください。',required:'企業名、法人番号、担当者、メールを入力してください。',failed:'現在送信できません。後ほど再度お試しください。',sent:'申請を送信しました。案件ID：',eye:'1%企業共有パートナー · 参加申請',hero:'企業の1%をどこから始められるか教えてください。',lead:'支援額の条件はありません。製品、専門性、仕事、人材、場所、ひとつのつながりから始められます。',steps:['企業情報','共有できる1%','連携方向','審査へ送信'],basic:'企業基本情報',company:'企業／店舗名',taxId:'法人番号',contact:'担当者',phone:'電話',region:'地域',share:'企業が現在共有できそうな1%',multi:'複数選択できます。「未定」でも構いません。',start:'企業はどこから始めたいですか？',after:'送信後の流れ',timeline:['RCSCAが企業情報とニーズを確認','適切な共有／連携ルートを確認','最初の実際の共有完了後に年間記録を作成','条件達成後に年間1%バッジを取得'],sending:'送信中…',submit:'参加申請を送信 →',previous:'← 前へ',next:'次へ →'},
 'ko':{options:['자금／물품','제품／서비스','전문 역량','임직원 참여','일자리','공간','인맥 연결','아직 미정'],directions:[['공익 돌봄','실제 필요, 공익 프로젝트 또는 임직원 활동에 참여합니다.'],['자원 연결','일자리, 인재, 전문성, 서비스 및 1% Network를 연결합니다.'],['ESG 프로젝트','기업 목표에서 출발해 실행 가능한 협력과 성과를 설계합니다.'],['먼저 상담','적합한 경로가 아직 불분명하면 RCSCA가 판단을 돕습니다.']],signin:'로그인한 뒤 기업 참여 신청을 제출해 주세요.',required:'기업명, 사업자번호, 담당자와 이메일을 입력해 주세요.',failed:'현재 제출할 수 없습니다. 잠시 후 다시 시도해 주세요.',sent:'신청을 제출했습니다. 건 ID: ',eye:'1% 기업 공유 파트너 · 참여 신청',hero:'기업의 1%를 어디에서 시작할 수 있는지 알려 주세요.',lead:'후원 금액 기준은 없습니다. 제품, 전문성, 일자리, 인력, 공간 또는 하나의 연결에서 시작할 수 있습니다.',steps:['기업 정보','공유 가능한 1%','협력 방향','검토 제출'],basic:'기업 기본 정보',company:'기업／매장명',taxId:'사업자번호',contact:'담당자',phone:'전화',region:'지역',share:'기업이 현재 공유할 수 있는 1%',multi:'복수 선택하거나 “아직 미정”을 선택할 수 있습니다.',start:'기업은 어디에서 시작하고 싶나요?',after:'제출 후 진행 과정',timeline:['RCSCA가 기업 정보와 필요를 확인','적합한 공유／협력 경로 확인','첫 실제 공유 완료 후 연간 공유 기록 생성','조건 충족 후 연간 1% 배지 획득'],sending:'제출 중…',submit:'참여 신청 제출 →',previous:'← 이전',next:'다음 →'}
};
export default function PartnerApply(){const {locale}=useI18n();const c=copy[locale];const [step,setStep]=useState(1),[selected,setSelected]=useState<string[]>([]),[direction,setDirection]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const [form,setForm]=useState({company:'',taxId:'',contact:'',email:'',phone:'',region:''});
 async function submit(){setMessage('');const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session){setMessage(c.signin);return}if(!form.company||!form.taxId||!form.contact||!form.email){setMessage(c.required);setStep(1);return}setBusy(true);const {data,error}=await s.rpc('submit_enterprise_application',{p_company_name:form.company,p_tax_id:form.taxId,p_contact_name:form.contact,p_contact_email:form.email,p_contact_phone:form.phone,p_region:form.region,p_share_options:selected,p_direction:direction||'consult'});setBusy(false);setMessage(error?c.failed:`${c.sent}${String(data).slice(0,8).toUpperCase()}`)}
 return <main className="flowPage"><SiteHeader/><section className="flowHero"><div className="portalWrap"><div className="eyebrow">{c.eye}</div><h1>{c.hero}</h1><p>{c.lead}</p></div></section><section className="portalSection"><div className="portalWrap flowShell"><div className="flowSteps">{c.steps.map((x:string,i:number)=><button key={x} className={step===i+1?'active':step>i+1?'done':''} onClick={()=>setStep(i+1)}><span>0{i+1}</span><b>{x}</b></button>)}</div><div className="flowPanel">
 {step===1&&<><small>STEP 01</small><h2>{c.basic}</h2><div className="briefFields"><input placeholder={c.company} value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><input placeholder={c.taxId} value={form.taxId} onChange={e=>setForm({...form,taxId:e.target.value})}/><input placeholder={c.contact} value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/><input placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder={c.phone} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder={c.region} value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></div></>}
 {step===2&&<><small>STEP 02</small><h2>{c.share}</h2><p>{c.multi}</p><div className="needGrid">{optionValues.map((value,i)=><label key={value}><input type="checkbox" checked={selected.includes(value)} onChange={()=>setSelected(v=>v.includes(value)?v.filter(y=>y!==value):[...v,value])}/><span>{c.options[i]}</span></label>)}</div></>}
 {step===3&&<><small>STEP 03</small><h2>{c.start}</h2><div className="choiceCards">{directionKeys.map((key,i)=><label key={key}><input name="direction" type="radio" checked={direction===key} onChange={()=>setDirection(key)}/><b>{c.directions[i][0]}</b><span>{c.directions[i][1]}</span></label>)}</div></>}
 {step===4&&<><small>STEP 04</small><h2>{c.after}</h2><div className="reviewTimeline">{c.timeline.map((x:string,i:number)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><button className="submitLead" disabled={busy} onClick={submit}>{busy?c.sending:c.submit}</button>{message&&<p className="formNote">{message}</p>}</>}
 <div className="flowNav"><button disabled={step===1} onClick={()=>setStep(Math.max(1,step-1))}>{c.previous}</button>{step<4&&<button className="primaryFlow" onClick={()=>setStep(Math.min(4,step+1))}>{c.next}</button>}</div></div></div></section></main>}
