'use client';
import {useEffect,useState} from 'react';import SiteHeader from '../../SiteHeader';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Source={invitation_id:string;source_type:string;accepted_at:string|null;inviter_display_name:string;team_name:string|null};
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'介紹來源',title:'記得從哪裡開始，但不把關係變成上下線。',lead:'介紹來源只用於歷史辨識與社群連結，不影響 XP、共享點、會籍、排序或任何利益。',loading:'正在讀取介紹來源…',teamInvite:'共享小隊邀請',source:'介紹來源',team:'加入時所屬小隊：',time:'確認時間：',recorded:'已記錄',note:'這筆來源是歷史紀錄，不代表推薦關係、上下線或利益分配。',empty:'目前沒有已確認的介紹來源',emptyLead:'你仍可正常使用 MY 1%；沒有介紹人不影響任何會員功能或權益。'},
 en:{eye:'Referral Source',title:'Remember where it began without turning relationships into a hierarchy.',lead:'Referral sources are used only for historical context and community connections. They do not affect XP, Sharing Points, membership, ranking, or benefits.',loading:'Loading referral source…',teamInvite:'Sharing Team invitation',source:'Referral source',team:'Team joined through: ',time:'Confirmed on: ',recorded:'Recorded',note:'This is a historical record. It does not represent a referral hierarchy, commission relationship, or benefit distribution.',empty:'No confirmed referral source',emptyLead:'You can use MY 1% normally. Having no referrer does not affect any member function or benefit.'},
 ja:{eye:'紹介元',title:'始まりは記録しても、関係を上下構造にはしません。',lead:'紹介元は履歴確認とコミュニティのつながりにのみ使用し、XP、共有ポイント、会員資格、順位、利益には影響しません。',loading:'紹介元を読み込み中…',teamInvite:'共有チームからの招待',source:'紹介元',team:'参加時の所属チーム：',time:'確認日：',recorded:'記録済み',note:'この情報は履歴記録であり、紹介の上下関係、コミッション、利益分配を示すものではありません。',empty:'確認済みの紹介元はありません',emptyLead:'紹介者がいなくてもMY 1%を通常どおり利用でき、会員機能や権利には影響しません。'},
 ko:{eye:'소개 경로',title:'시작 경로는 기억하되 관계를 상하 구조로 만들지 않습니다.',lead:'소개 경로는 이력 확인과 커뮤니티 연결에만 사용되며 XP, 공유 포인트, 회원 자격, 순위 또는 이익에 영향을 주지 않습니다.',loading:'소개 경로를 불러오는 중…',teamInvite:'공유 팀 초대',source:'소개 경로',team:'가입 당시 소속 팀: ',time:'확인일: ',recorded:'기록됨',note:'이 정보는 이력 기록일 뿐 추천 상하 관계, 수수료 관계 또는 이익 배분을 의미하지 않습니다.',empty:'확인된 소개 경로가 없습니다',emptyLead:'소개자가 없어도 MY 1%를 정상적으로 사용할 수 있으며 회원 기능이나 권리에 영향을 주지 않습니다.'}
};
const dateLocale:Record<Locale,string>={'zh-Hant':'zh-TW',en:'en-US',ja:'ja-JP',ko:'ko-KR'};
export default function ReferralSource(){const{locale}=useI18n();const c=copy[locale];const[row,setRow]=useState<Source|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data}=await s.rpc('account_referral_source');setRow((data||[])[0]||null);setLoading(false)})()},[locale]);return <main className="accountPage"><SiteHeader/><section className="accountHero"><div className="portalWrap"><div className="eyebrow">{c.eye}</div><h1>{c.title}</h1><p>{c.lead}</p></div></section><section className="portalSection"><div className="portalWrap">{loading?<div className="liveAccountLoading">{c.loading}</div>:row?<article className="caseCard"><small>{row.source_type==='team_invite'?c.teamInvite:c.source}</small><h2>{row.inviter_display_name}</h2>{row.team_name&&<p>{c.team}<strong>{row.team_name}</strong></p>}<p>{c.time}{row.accepted_at?new Date(row.accepted_at).toLocaleDateString(dateLocale[locale]):c.recorded}</p><p className="microNote">{c.note}</p></article>:<div className="privacyCallout"><strong>{c.empty}</strong><p>{c.emptyLead}</p></div>}</div></section></main>}
