'use client';
import SiteHeader from '../../SiteHeader';import {FormEvent,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';import {networkCopy} from '../../networkCopy';
const flow:Record<Locale,any>={
 'zh-Hant':{signin:'請先登入，再提出人才媒合需求。',member:'這項深層媒合功能限 RCSCA MEMBER 使用。',fail:'送出失敗，請稍後再試。',done:'人才需求已送出。後續媒合與回應可在「我的需求與進度」查看。',title:'人才需求',find:'尋找',region:'地區',types:['正職','兼職','短期／活動','接案','志工／公益協作','其他']},
 en:{signin:'Please sign in before submitting a talent request.',member:'This deeper matching feature is available to RCSCA MEMBER accounts only.',fail:'Submission failed. Please try again later.',done:'Talent request submitted. Follow matching and responses under My Requests & Progress.',title:'Talent request',find:'Seeking',region:'Region',types:['Full-time','Part-time','Short-term / event','Freelance','Volunteer / community collaboration','Other']},
 ja:{signin:'ログインしてから人材マッチング依頼を送信してください。',member:'この深層マッチング機能はRCSCA MEMBER限定です。',fail:'送信できませんでした。後ほど再度お試しください。',done:'人材依頼を送信しました。マッチングと返信は「依頼と進捗」で確認できます。',title:'人材依頼',find:'募集',region:'地域',types:['正社員','パートタイム','短期／イベント','業務委託','ボランティア／公益協働','その他']},
 ko:{signin:'로그인 후 인재 매칭 요청을 제출해 주세요.',member:'이 심화 매칭 기능은 RCSCA MEMBER만 사용할 수 있습니다.',fail:'제출하지 못했습니다. 잠시 후 다시 시도해 주세요.',done:'인재 요청을 제출했습니다. 매칭과 답변은 나의 요청 및 진행에서 확인할 수 있습니다.',title:'인재 요청',find:'모집',region:'지역',types:['정규직','파트타임','단기／행사','프리랜서','자원봉사／공익 협업','기타']}
};
export default function TalentRequest(){const{locale}=useI18n(),c=networkCopy[locale],f=flow[locale];const[skill,setSkill]=useState(''),[region,setRegion]=useState(''),[workType,setWorkType]=useState(''),[detail,setDetail]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false);async function submit(e:FormEvent){e.preventDefault();setSending(true);setMessage('');try{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session){setMessage(f.signin);return}const{error}=await s.rpc('member_submit_network_request',{p_request_kind:'talent',p_title:`${f.title}｜${skill}${region?`｜${region}`:''}`,p_public_summary:`${f.find} ${skill}${workType?`，${workType}`:''}${region?`，${f.region} ${region}`:''}`,p_private_detail:detail,p_requester_enterprise_id:undefined});if(error){setMessage(error.message.includes('active_membership_required')?f.member:f.fail);return}setMessage(f.done);setSkill('');setRegion('');setWorkType('');setDetail('')}finally{setSending(false)}}return <main className="flowPage"><SiteHeader/><section className="flowHero"><div className="portalWrap"><div className="eyebrow">{c.talentEye}</div><h1>{c.talentTitle}</h1><p>{c.talentLead}</p></div></section><section className="portalSection"><div className="portalWrap actionForm"><form onSubmit={submit}><div className="briefFields"><label><span className="srOnly">{c.skill}</span><input required placeholder={c.skill} value={skill} onChange={e=>setSkill(e.target.value)}/></label><label><span className="srOnly">{c.workRegion}</span><input required placeholder={c.workRegion} value={region} onChange={e=>setRegion(e.target.value)}/></label><label><span className="srOnly">{c.workType}</span><select required value={workType} onChange={e=>setWorkType(e.target.value)}><option value="">{c.workType}</option>{f.types.map((x:string)=><option key={x}>{x}</option>)}</select></label><label><span className="srOnly">{c.talentDetail}</span><textarea required placeholder={c.talentDetail} value={detail} onChange={e=>setDetail(e.target.value)}/></label></div><button className="submitLead" disabled={sending}>{sending?c.sending:c.submitTalent}</button>{message&&<div className="authMessage sent" role="status" aria-live="polite">{message}</div>}</form><aside><b>{c.noList}</b><p>{c.noListDesc}</p><b>{c.conditions}</b><p>{c.conditionsDesc}</p></aside></div></section></main>}
