'use client';
import {FormEvent,useEffect,useState} from 'react';
import SiteHeader from '../../SiteHeader';
import {useI18n} from '../../i18n';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';

const copy:any={
'zh-Hant':{eye:'帳號與安全',title:'登入憑證和會員資料分開管理。',lead:'Email 與密碼屬於登入安全設定；會員身份、會籍、共享等級與企業權限不會因修改登入資料而改變。',signin:'請先登入',signinLead:'登入後才能管理帳號安全設定。',go:'前往登入 →',changeEmail:'變更 Email',current:'目前 Email',newEmail:'新的 Email',sendEmail:'送出 Email 變更',password:'登入密碼',update:'更新密碼',newPass:'新密碼',again:'再次輸入',security:'安全原則',securityLead:'RCSCA 不會在一般會員資料表保存你的登入密碼。忘記密碼或無法登入時，應走驗證過的帳號復原流程，不由後台人員查看或代讀原密碼。',emailLabel:'登入 Email',reset:'驗證完成。請在下方設定新的登入密碼。',different:'請輸入不同的新 Email。',emailFailed:'Email 更新申請未完成，請確認格式或稍後再試。',emailSent:'已送出 Email 變更申請；若系統要求驗證，請完成信箱中的確認步驟後才會生效。',short:'新密碼至少需要 8 個字元。',mismatch:'兩次輸入的密碼不一致。',passwordFailed:'密碼更新未完成，請稍後再試。',passwordDone:'密碼已更新。'},
'en':{eye:'Account & Security',title:'Sign-in credentials and membership data are managed separately.',lead:'Email and password are security credentials. Changing them does not alter membership, Sharing Level or organization permissions.',signin:'Please sign in',signinLead:'Sign in to manage account security.',go:'Go to sign in →',changeEmail:'Change email',current:'Current email',newEmail:'New email',sendEmail:'Submit email change',password:'Sign-in password',update:'Update password',newPass:'New password',again:'Enter again',security:'Security principle',securityLead:'RCSCA does not store your sign-in password in general member records. Use the verified account recovery flow if you forget your password; staff cannot view or read it for you.',emailLabel:'Sign-in email',reset:'Verification completed. Set a new sign-in password below.',different:'Enter a different new email address.',emailFailed:'Email update request failed. Check the format or try again later.',emailSent:'Email change submitted. Complete any confirmation step sent to your inbox before it takes effect.',short:'The new password must be at least 8 characters.',mismatch:'The two passwords do not match.',passwordFailed:'Password update failed. Please try again later.',passwordDone:'Password updated.'},
'ja':{eye:'アカウントとセキュリティ',title:'ログイン情報と会員データは分けて管理します。',lead:'メールとパスワードはログイン用の安全設定です。変更しても会員資格、共有レベル、企業権限は変わりません。',signin:'ログインしてください',signinLead:'ログイン後にセキュリティ設定を管理できます。',go:'ログインへ →',changeEmail:'メールを変更',current:'現在のメール',newEmail:'新しいメール',sendEmail:'メール変更を送信',password:'ログインパスワード',update:'パスワードを更新',newPass:'新しいパスワード',again:'もう一度入力',security:'セキュリティ原則',securityLead:'RCSCA は一般会員データにログインパスワードを保存しません。忘れた場合は本人確認済みのアカウント復旧フローを利用し、運営が元のパスワードを閲覧することはありません。',emailLabel:'ログインメール',reset:'確認が完了しました。下で新しいログインパスワードを設定してください。',different:'現在と異なるメールを入力してください。',emailFailed:'メール変更を完了できません。形式を確認するか、後ほど再度お試しください。',emailSent:'メール変更を送信しました。確認が必要な場合は、受信メールの手続きを完了すると反映されます。',short:'新しいパスワードは8文字以上必要です。',mismatch:'2回入力したパスワードが一致しません。',passwordFailed:'パスワードを更新できません。後ほど再度お試しください。',passwordDone:'パスワードを更新しました。'},
'ko':{eye:'계정 및 보안',title:'로그인 정보와 회원 데이터는 분리해 관리합니다.',lead:'이메일과 비밀번호는 로그인 보안 설정입니다. 변경해도 회원 자격, 공유 레벨, 기업 권한은 바뀌지 않습니다.',signin:'로그인이 필요합니다',signinLead:'로그인 후 계정 보안 설정을 관리할 수 있습니다.',go:'로그인으로 →',changeEmail:'이메일 변경',current:'현재 이메일',newEmail:'새 이메일',sendEmail:'이메일 변경 요청',password:'로그인 비밀번호',update:'비밀번호 변경',newPass:'새 비밀번호',again:'다시 입력',security:'보안 원칙',securityLead:'RCSCA는 일반 회원 데이터에 로그인 비밀번호를 저장하지 않습니다. 비밀번호를 잊었거나 로그인할 수 없을 때는 인증된 계정 복구 절차를 이용하며 운영자가 기존 비밀번호를 열람하지 않습니다.',emailLabel:'로그인 이메일',reset:'인증이 완료되었습니다. 아래에서 새 로그인 비밀번호를 설정하세요.',different:'현재와 다른 새 이메일을 입력해 주세요.',emailFailed:'이메일 변경 요청을 완료하지 못했습니다. 형식을 확인하거나 잠시 후 다시 시도해 주세요.',emailSent:'이메일 변경 요청을 제출했습니다. 인증이 필요한 경우 받은 편지함의 확인 절차를 완료해야 적용됩니다.',short:'새 비밀번호는 8자 이상이어야 합니다.',mismatch:'두 비밀번호가 일치하지 않습니다.',passwordFailed:'비밀번호를 변경하지 못했습니다. 잠시 후 다시 시도해 주세요.',passwordDone:'비밀번호를 변경했습니다.'}};
export default function AccountSecurity(){
 const{locale}=useI18n();const c=copy[locale];
 const[email,setEmail]=useState(''),[newEmail,setNewEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[msg,setMsg]=useState(''),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('reset')==='1')setMsg(c.reset);(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(session){setSignedIn(true);setEmail(session.user.email||'');setNewEmail(session.user.email||'')}})()},[locale]);
 async function changeEmail(e:FormEvent){e.preventDefault();if(!newEmail.trim()||newEmail.trim().toLowerCase()===email.toLowerCase()){setMsg(c.different);return}setBusy(true);const s=getSupabaseBrowserClient();const{error}=await s.auth.updateUser({email:newEmail.trim()});setBusy(false);setMsg(error?c.emailFailed:c.emailSent)}
 async function changePassword(e:FormEvent){e.preventDefault();if(password.length<8){setMsg(c.short);return}if(password!==confirmPassword){setMsg(c.mismatch);return}setBusy(true);const s=getSupabaseBrowserClient();const{error}=await s.auth.updateUser({password});setBusy(false);if(error){setMsg(c.passwordFailed);return}setPassword('');setConfirmPassword('');setMsg(c.passwordDone)}
 return <main className="flowPage"><SiteHeader/><section className="flowHero"><div className="portalWrap"><div className="eyebrow">{c.eye}</div><h1>{c.title}</h1><p>{c.lead}</p></div></section><section className="portalSection"><div className="portalWrap">{!signedIn?<div className="privacyCallout"><strong>{c.signin}</strong><p>{c.signinLead}</p><a href="/login">{c.go}</a></div>:<div className="portalGrid two"><form className="authForm" onSubmit={changeEmail}><small>{c.emailLabel}</small><h2>{c.changeEmail}</h2><label>{c.current}<input value={email} disabled/></label><label>{c.newEmail}<input type="email" required value={newEmail} onChange={e=>setNewEmail(e.target.value)}/></label><button disabled={busy}>{c.sendEmail}</button></form><form className="authForm" onSubmit={changePassword}><small>{c.password}</small><h2>{c.update}</h2><label>{c.newPass}<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>{c.again}<input type="password" minLength={8} required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button disabled={busy}>{c.update}</button></form></div>}{msg&&<div className="workflowNotice">{msg}</div>}<div className="privacyCallout"><strong>{c.security}</strong><p>{c.securityLead}</p></div></div></section></main>
}
