'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../../../lib/supabase-browser';import {Locale,useI18n} from '../../../../i18n';
const copy:Record<Locale,any>={
 'zh-Hant':{signin:'請先登入。',notFound:'找不到案件，或你沒有查看權限。',sendFail:'目前無法送出，請稍後再試。',sent:'補充資料已送出。',loading:'正在讀取案件…',unavailable:'無法讀取案件',private:'需求案件只開放本人與具個案權限的承辦查看。',back:'回到我的進度 →',kind:'關懷需求',updated:'更新 ',timeline:'案件時間軸',building:'案件歷程建立中。',needPlaceholder:'補上 RCSCA 請你提供的資料',replyPlaceholder:'補充目前狀況或回覆 RCSCA',submit:'送出補充／回覆',backBottom:'← 回到我的進度',labels:{submitted:'已送出',under_review:'評估中',needs_info:'需要補充',approved:'已核准',matched:'資源媒合中',completed:'已完成',rejected:'未承接',cancelled:'已取消'},events:{created:'建立需求',status_changed:'進度更新',needs_info:'需要補充資料',owner_reply:'我的補充／回覆',completed:'案件完成',rejected:'案件結果',fallback:'案件更新'}},
 en:{signin:'Please sign in.',notFound:'The case could not be found, or you do not have permission to view it.',sendFail:'The reply cannot be submitted right now. Please try again later.',sent:'Additional information submitted.',loading:'Loading case…',unavailable:'Unable to load case',private:'Request cases are visible only to the owner and authorized case staff.',back:'Back to my progress →',kind:'Care request',updated:'Updated ',timeline:'Case timeline',building:'The case history is being prepared.',needPlaceholder:'Add the information requested by RCSCA',replyPlaceholder:'Add an update or reply to RCSCA',submit:'Submit update / reply',backBottom:'← Back to my progress',labels:{submitted:'Submitted',under_review:'Under review',needs_info:'More information needed',approved:'Approved',matched:'Resource matching',completed:'Completed',rejected:'Not accepted',cancelled:'Cancelled'},events:{created:'Request created',status_changed:'Progress updated',needs_info:'More information requested',owner_reply:'My update / reply',completed:'Case completed',rejected:'Case outcome',fallback:'Case updated'}},
 ja:{signin:'ログインしてください。',notFound:'案件が見つからないか、閲覧権限がありません。',sendFail:'現在送信できません。後ほど再度お試しください。',sent:'追加情報を送信しました。',loading:'案件を読み込み中…',unavailable:'案件を読み込めません',private:'依頼案件を確認できるのは本人と権限を持つ担当者だけです。',back:'自分の進捗へ戻る →',kind:'ケアの依頼',updated:'更新 ',timeline:'案件のタイムライン',building:'案件履歴を作成中です。',needPlaceholder:'RCSCAから依頼された情報を追加',replyPlaceholder:'現在の状況を追加、またはRCSCAへ返信',submit:'追加情報／返信を送信',backBottom:'← 自分の進捗へ戻る',labels:{submitted:'提出済み',under_review:'審査中',needs_info:'情報の追加が必要',approved:'承認済み',matched:'資源マッチング中',completed:'完了',rejected:'受付不可',cancelled:'キャンセル済み'},events:{created:'依頼を作成',status_changed:'進捗を更新',needs_info:'情報の追加が必要',owner_reply:'自分の追加情報／返信',completed:'案件完了',rejected:'案件結果',fallback:'案件更新'}},
 ko:{signin:'로그인이 필요합니다.',notFound:'사례를 찾을 수 없거나 조회 권한이 없습니다.',sendFail:'현재 제출할 수 없습니다. 잠시 후 다시 시도해 주세요.',sent:'추가 정보를 제출했습니다.',loading:'사례를 불러오는 중…',unavailable:'사례를 불러올 수 없습니다',private:'요청 사례는 본인과 권한이 있는 담당자만 확인할 수 있습니다.',back:'나의 진행으로 →',kind:'돌봄 요청',updated:'업데이트 ',timeline:'사례 타임라인',building:'사례 이력을 준비 중입니다.',needPlaceholder:'RCSCA에서 요청한 정보를 추가하세요',replyPlaceholder:'현재 상황을 추가하거나 RCSCA에 답변하세요',submit:'추가 정보／답변 제출',backBottom:'← 나의 진행으로',labels:{submitted:'제출됨',under_review:'검토 중',needs_info:'추가 정보 필요',approved:'승인됨',matched:'자원 매칭 중',completed:'완료',rejected:'접수되지 않음',cancelled:'취소됨'},events:{created:'요청 생성',status_changed:'진행 업데이트',needs_info:'추가 정보 요청',owner_reply:'나의 추가 정보／답변',completed:'사례 완료',rejected:'사례 결과',fallback:'사례 업데이트'}}
};
const dateLocale:Record<Locale,string>={'zh-Hant':'zh-TW',en:'en-US',ja:'ja-JP',ko:'ko-KR'};
export default function LiveSupportCase({id}:{id:string}){const{locale}=useI18n();const c=copy[locale];const [loading,setLoading]=useState(true),[row,setRow]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[reply,setReply]=useState(''),[notice,setNotice]=useState('');
 async function load(){const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session){setNotice(c.signin);setLoading(false);return;}const [{data,error},{data:ev}]=await Promise.all([s.from('support_cases').select('id,title,public_summary,status,created_at,updated_at').eq('id',id).maybeSingle(),s.from('support_case_events').select('id,event_type,status,note,created_at').eq('case_id',id).order('created_at',{ascending:true})]);if(error||!data)setNotice(c.notFound);else setRow(data);setEvents(ev||[]);setLoading(false)}
 useEffect(()=>{load()},[id,locale]);
 async function send(){if(!reply.trim())return;const s=getSupabaseBrowserClient();const {error}=await s.rpc('owner_reply_support_case',{p_case_id:id,p_message:reply.trim()});setNotice(error?c.sendFail:c.sent);if(!error){setReply('');await load()}}
 if(loading)return <p>{c.loading}</p>;if(!row)return <div className="privacyCallout"><strong>{notice||c.unavailable}</strong><p>{c.private}</p><a href="/account/requests">{c.back}</a></div>;
 const closed=['completed','rejected','cancelled'].includes(row.status);
 return <div className="caseCard"><div className="stateMeta"><small>{c.kind}</small><span>{row.id.slice(0,8)}</span></div><h2>{row.title}</h2><div className="stateRow"><span className={`statusChip status-${row.status}`}>{c.labels[row.status]||row.status}</span><span>{c.updated}{new Date(row.updated_at).toLocaleDateString(dateLocale[locale])}</span></div>{row.public_summary&&<p>{row.public_summary}</p>}<div className="caseTimeline"><h4>{c.timeline}</h4>{events.length?events.map(e=><div className="timelineItem" key={e.id}><span>{new Date(e.created_at).toLocaleDateString(dateLocale[locale])}</span><div><strong>{c.events[e.event_type]||c.events.fallback}</strong>{e.note&&<p>{e.note}</p>}</div></div>):<p className="formNote">{c.building}</p>}</div>{!closed&&<div className="caseReply"><textarea placeholder={row.status==='needs_info'?c.needPlaceholder:c.replyPlaceholder} value={reply} onChange={e=>setReply(e.target.value)}/><button onClick={send}>{c.submit}</button></div>}{notice&&<p className="formNote">{notice}</p>}<a className="textRoute" href="/account/requests">{c.backBottom}</a></div>;
}
