'use client';
import {FormEvent,useState} from 'react';
import SiteHeader from '../../SiteHeader';
import {useI18n} from '../../i18n';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';
const copy:any={
'zh-Hant':{eye:'帳號復原',title:'忘記密碼，不需要由後台查看你的舊密碼。',lead:'輸入登入 Email；系統會寄送一次性的安全連結，完成信箱驗證後再設定新密碼。',email:'登入 Email',sending:'寄送中…',send:'寄送密碼重設連結',ok:'密碼重設連結已寄出。請從信箱完成驗證，再設定新密碼。',fail:'目前無法寄出重設連結，請確認 Email 或稍後再試。',back:'返回登入 →'},
'en':{eye:'Account recovery',title:'Forgot your password? Your old password never needs to be viewed by staff.',lead:'Enter your sign-in email. We will send a one-time secure link so you can verify your inbox and set a new password.',email:'Sign-in email',sending:'Sending…',send:'Send password reset link',ok:'Password reset link sent. Verify it from your inbox, then set a new password.',fail:'We could not send the reset link. Check your email or try again later.',back:'Back to sign in →'},
'ja':{eye:'アカウント復旧',title:'パスワードを忘れても、運営が以前のパスワードを見る必要はありません。',lead:'ログイン用メールアドレスを入力してください。本人確認用の一度限りの安全なリンクを送信し、確認後に新しいパスワードを設定できます。',email:'ログイン用メール',sending:'送信中…',send:'パスワード再設定リンクを送信',ok:'再設定リンクを送信しました。メールで本人確認後、新しいパスワードを設定してください。',fail:'再設定リンクを送信できませんでした。メールアドレスを確認するか、後でもう一度お試しください。',back:'ログインへ戻る →'},
'ko':{eye:'계정 복구',title:'비밀번호를 잊어도 운영자가 기존 비밀번호를 확인할 필요는 없습니다.',lead:'로그인 이메일을 입력하세요. 일회용 보안 링크를 보내며 이메일 확인 후 새 비밀번호를 설정할 수 있습니다.',email:'로그인 이메일',sending:'전송 중…',send:'비밀번호 재설정 링크 보내기',ok:'재설정 링크를 보냈습니다. 이메일 인증 후 새 비밀번호를 설정하세요.',fail:'재설정 링크를 보낼 수 없습니다. 이메일을 확인하거나 잠시 후 다시 시도하세요.',back:'로그인으로 →'}};
export default function RecoverAccount(){const{locale}=useI18n();const c=copy[locale];const[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const s=getSupabaseBrowserClient();const callback=new URL('/auth/callback',window.location.origin);callback.searchParams.set('next','/account/security?reset=1');const{error}=await s.auth.resetPasswordForEmail(email.trim(),{redirectTo:callback.toString()});if(error)throw error;setMsg(c.ok)}catch{setMsg(c.fail)}finally{setBusy(false)}}return <main className="authPage"><SiteHeader/><section className="authShell"><div className="eyebrow">{c.eye}</div><h1>{c.title}</h1><p>{c.lead}</p><form className="authForm" onSubmit={submit}><label>{c.email}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><button disabled={busy}>{busy?c.sending:c.send}</button></form>{msg&&<div className="workflowNotice">{msg}</div>}<p className="authAssist"><a href="/login">{c.back}</a></p></section></main>}
