'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'成果匯出準備',title:'先檢查資料品質，再帶走年度成果。',lead:'只有已核准、可供報告使用且必要欄位完整的成果才進入匯出；缺漏會明確列出，不用漂亮格式掩蓋資料問題。',ready:'可匯出',issues:'待補資料',quality:'資料品質',items:'筆',needs:'需要整理',passed:'已通過',current:'目前待補',untitled:'未命名成果',unverified:'來源尚未完成核實',download:'匯出可用成果資料',done:'成果資料已匯出。',failed:'目前無法匯出成果資料，請稍後再試。'},
 en:{eye:'Outcome Export Readiness',title:'Check data quality before taking annual outcomes forward.',lead:'Only approved, report-ready outcomes with complete required fields are exported. Gaps are listed clearly instead of hidden by polished formatting.',ready:'Exportable',issues:'Needs data',quality:'Data quality',items:'items',needs:'Needs work',passed:'Passed',current:'Current gaps',untitled:'Untitled outcome',unverified:'Source verification incomplete',download:'Export report-ready outcomes',done:'Outcome data exported.',failed:'Outcome data cannot be exported right now. Please try again later.'},
 ja:{eye:'成果エクスポート準備',title:'年間成果を持ち出す前に、データ品質を確認します。',lead:'承認済み・報告利用可・必須項目完備の成果だけを出力します。不足は明示し、見栄えで問題を隠しません。',ready:'出力可能',issues:'要追加',quality:'データ品質',items:'件',needs:'整理が必要',passed:'合格',current:'現在の不足',untitled:'名称未設定の成果',unverified:'出典確認が未完了',download:'利用可能な成果データを出力',done:'成果データを出力しました。',failed:'現在、成果データを出力できません。後ほど再度お試しください。'},
 ko:{eye:'성과 내보내기 준비',title:'연간 성과를 가져가기 전에 데이터 품질을 확인합니다.',lead:'승인되고 보고서 사용 가능하며 필수 항목이 완성된 성과만 내보냅니다. 누락은 명확히 표시하며 보기 좋은 형식으로 문제를 숨기지 않습니다.',ready:'내보내기 가능',issues:'보완 필요',quality:'데이터 품질',items:'건',needs:'정리 필요',passed:'통과',current:'현재 보완 항목',untitled:'이름 없는 성과',unverified:'출처 확인 미완료',download:'사용 가능한 성과 데이터 내보내기',done:'성과 데이터를 내보냈습니다.',failed:'현재 성과 데이터를 내보낼 수 없습니다. 잠시 후 다시 시도해 주세요.'}
};
export default function LiveESGExport(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<any[]>([]),[notice,setNotice]=useState('');useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const{data}=await s.from('enterprise_esg_evidence_chain').select('*').eq('enterprise_id',eu.enterprise_id);setRows(data||[])})()},[locale]);if(!rows.length)return null;const ready=rows.filter(r=>r.report_ready&&r.source_verified);const issues=rows.filter(r=>!r.source_verified);function download(){try{const payload=ready.map(r=>({title:r.title,period:r.period_label,status:r.status,summary:r.summary,metric_label:r.metric_label,metric_value:r.metric_value,metric_unit:r.metric_unit,sdg_tags:r.sdg_tags,evidence_note:r.evidence_note,source_type:r.source_type,source_reference:r.source_reference,source_verified:r.source_verified}));const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='RCSCA-ESG-results.json';a.click();URL.revokeObjectURL(a.href);setNotice(c.done)}catch{setNotice(c.failed)}}return <section className="esgAnnualPanel"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{c.title}</h2></div><p>{c.lead}</p></div><div className="portalGrid three"><article><small>{c.ready}</small><h3>{ready.length} {c.items}</h3></article><article><small>{c.issues}</small><h3>{issues.length} {c.items}</h3></article><article><small>{c.quality}</small><h3>{issues.length?c.needs:c.passed}</h3></article></div>{issues.length>0&&<div className="privacyCallout"><strong>{c.current}</strong>{issues.slice(0,5).map(r=><p key={r.id}>{r.title||c.untitled}：{r.source_verified?'':c.unverified}</p>)}</div>}<button className="esgLead" disabled={!ready.length} onClick={download}>{c.download}</button>{notice&&<p className="workflowNotice" role="status" aria-live="polite">{notice}</p>}</section>}
