'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Asset={id:string;title:string;asset_type:string;period_label:string|null;summary:string|null;status:string;evidence_note:string|null;metric_label:string|null;metric_value:number|null;metric_unit:string|null;sdg_tags:string[];report_ready:boolean};
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'企業 ESG 素材庫',title:'把完成的共享，整理成企業真正能使用的成果。',lead:'每一筆報告素材都保留核實依據；只使用可證明的成果，不把捐款金額直接等同社會影響力。',preparing:'成果素材整理中',evidence:'核實依據：',ready:'可供 ESG／永續報告使用',approved:'已核准',review:'整理／審核中',empty:'目前尚無已建立的 ESG 成果素材；完成並核實的合作之後會從這裡整理。'},
 en:{eye:'Organization ESG Asset Library',title:'Turn completed sharing into outcomes the organization can actually use.',lead:'Every reporting asset keeps its verification basis. Only demonstrable outcomes are used; donation amounts are not treated as social impact.',preparing:'Outcome asset in preparation',evidence:'Verification basis: ',ready:'Ready for ESG / sustainability reporting',approved:'Approved',review:'Preparing / under review',empty:'No ESG outcome assets have been created yet. Completed and verified collaborations will be organized here.'},
 ja:{eye:'企業ESG素材ライブラリ',title:'完了した共有を、企業が実際に使える成果へ。',lead:'各レポート素材には確認根拠を保持します。証明できる成果だけを使用し、寄付額を社会的インパクトと同一視しません。',preparing:'成果素材を整理中',evidence:'確認根拠：',ready:'ESG／サステナビリティ報告に使用可能',approved:'承認済み',review:'整理／審査中',empty:'ESG成果素材はまだありません。完了・確認済みの連携成果をここで整理します。'},
 ko:{eye:'기업 ESG 자료 라이브러리',title:'완료된 공유를 기업이 실제로 활용할 수 있는 성과로 정리합니다.',lead:'각 보고 자료에는 확인 근거를 보관합니다. 입증 가능한 성과만 사용하며 기부 금액을 사회적 영향과 동일시하지 않습니다.',preparing:'성과 자료 정리 중',evidence:'확인 근거: ',ready:'ESG／지속가능경영 보고서에 사용 가능',approved:'승인됨',review:'정리／검토 중',empty:'아직 ESG 성과 자료가 없습니다. 완료되고 확인된 협력 성과를 여기에서 정리합니다.'}
};
export default function LiveESGAssets(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<Asset[]>([]),[signed,setSigned]=useState(false);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;setSigned(true);const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const{data}=await s.from('enterprise_esg_assets').select('id,title,asset_type,period_label,summary,status,evidence_note,metric_label,metric_value,metric_unit,sdg_tags,report_ready').eq('enterprise_id',eu.enterprise_id).order('created_at',{ascending:false});setRows((data||[]) as Asset[])})()},[locale]);if(!signed)return null;return <section className="esgAssetPanel"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{c.title}</h2></div><p>{c.lead}</p></div>{rows.length?<div className="assetGrid">{rows.map(x=><article key={x.id}><small>{x.asset_type}{x.period_label?` · ${x.period_label}`:''}</small><h3>{x.title}</h3><p>{x.summary||c.preparing}</p>{x.metric_label&&x.metric_value!==null&&<div className="esgMetric"><strong>{x.metric_value}{x.metric_unit||''}</strong><span>{x.metric_label}</span></div>}{x.sdg_tags?.length>0&&<p className="esgTags">{x.sdg_tags.join(' · ')}</p>}{x.evidence_note&&<p className="evidenceNote">{c.evidence}{x.evidence_note}</p>}<b>{x.status==='approved'&&x.report_ready?c.ready:x.status==='approved'?c.approved:c.review}</b></article>)}</div>:<div className="emptyData">{c.empty}</div>}</section>}
