'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Summary={approved_shares:number;completed_network_requests:number;completed_network_matches:number};
const copy:Record<Locale,any>={
 'zh-Hant':{signin:'登入企業帳號後，可查看由已核實資料自動彙整的成果。',unlinked:'這個帳號尚未連結企業身份。',loading:'正在彙整企業共享成果…',private:'企業成果屬於登入後資料',verified:'已核實成果',shares:'核准共享項目',requests:'完成 Network 需求',matches:'完成媒合'},
 en:{signin:'Sign in with an organization account to view outcomes compiled from verified data.',unlinked:'This account is not linked to an organization.',loading:'Compiling organization sharing outcomes…',private:'Organization outcomes require sign-in',verified:'Verified outcomes',shares:'Approved sharing items',requests:'Completed Network requests',matches:'Completed matches'},
 ja:{signin:'企業アカウントでログインすると、確認済みデータから集計された成果を確認できます。',unlinked:'このアカウントは企業情報に連携されていません。',loading:'企業の共有成果を集計中…',private:'企業成果はログイン後に表示されます',verified:'確認済み成果',shares:'承認済み共有項目',requests:'完了したNetwork依頼',matches:'完了したマッチング'},
 ko:{signin:'기업 계정으로 로그인하면 확인된 데이터에서 집계된 성과를 볼 수 있습니다.',unlinked:'이 계정은 기업 정보에 연결되어 있지 않습니다.',loading:'기업 공유 성과를 집계하는 중…',private:'기업 성과는 로그인 후 확인할 수 있습니다',verified:'확인된 성과',shares:'승인된 공유 항목',requests:'완료된 Network 요청',matches:'완료된 매칭'}
};
export default function LiveEnterpriseImpact(){const{locale}=useI18n();const c=copy[locale];const[loading,setLoading]=useState(true),[name,setName]=useState(''),[m,setM]=useState<Summary|null>(null),[msg,setMsg]=useState('');useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session){setMsg(c.signin);setLoading(false);return}const{data:eu}=await s.from('enterprise_users').select('enterprise_id,enterprises(display_name,legal_name)').eq('user_id',session.user.id).limit(1).maybeSingle();const ent:any=(eu as any)?.enterprises;if(!ent){setMsg(c.unlinked);setLoading(false);return}setName(ent.display_name||ent.legal_name);const{data}=await s.from('enterprise_impact_summary').select('approved_shares,completed_network_requests,completed_network_matches').eq('enterprise_id',(eu as any).enterprise_id).maybeSingle();setM((data as Summary)||{approved_shares:0,completed_network_requests:0,completed_network_matches:0});setLoading(false)})()},[locale]);if(loading)return <div className="liveAccountLoading">{c.loading}</div>;if(msg)return <div className="privacyCallout"><strong>{c.private}</strong><p>{msg}</p></div>;return <><div className="impactOwner">{name} · {c.verified}</div><div className="metricGrid impactMetrics"><div><strong>{m?.approved_shares||0}</strong><span>{c.shares}</span></div><div><strong>{m?.completed_network_requests||0}</strong><span>{c.requests}</span></div><div><strong>{m?.completed_network_matches||0}</strong><span>{c.matches}</span></div></div></>}
