'use client';
import {useEffect,useMemo,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
const copy:Record<Locale,any>={
 'zh-Hant':{company:'企業夥伴',period:'未設定期間',eye:'正式年度成果報告',title:'可交付 ESG 成果摘要',lead:'只納入已通過內容完整性、RCSCA 核實與來源證據鏈檢查的成果。這是合作成果紀錄，不代表第三方 ESG 認證或確信。',items:'筆可交付成果',sdg:'SDG 對應：',evidence:'核實依據：',source:'來源：',verified:'已核實來源',print:'列印／另存年度成果報告',note:'本報告由 RCSCA 平台依已核實合作紀錄整理，供企業內部管理與永續報告素材使用；不構成會計、查證、認證或第三方確信意見。'},
 en:{company:'Organization Partner',period:'Period not set',eye:'Formal Annual Outcome Report',title:'Deliverable ESG outcome summary',lead:'Only outcomes that pass completeness, RCSCA verification, and source evidence-chain checks are included. This records collaboration outcomes and is not third-party ESG certification or assurance.',items:'deliverable outcomes',sdg:'SDG mapping: ',evidence:'Verification basis: ',source:'Source: ',verified:'Verified source',print:'Print / save annual outcome report',note:'This report is compiled by the RCSCA platform from verified collaboration records for internal management and sustainability-reporting materials. It is not accounting, verification, certification, or third-party assurance.'},
 ja:{company:'企業パートナー',period:'期間未設定',eye:'正式年間成果報告',title:'納品可能なESG成果サマリー',lead:'内容完全性、RCSCA確認、出典証拠チェーンの検査を通過した成果だけを掲載します。これは連携成果の記録であり、第三者ESG認証や保証ではありません。',items:'件の納品可能な成果',sdg:'SDG対応：',evidence:'確認根拠：',source:'出典：',verified:'確認済み出典',print:'年間成果報告を印刷／保存',note:'本報告はRCSCAプラットフォームが確認済み連携記録から整理し、社内管理とサステナビリティ報告素材に利用するものです。会計、検証、認証、第三者保証を構成しません。'},
 ko:{company:'기업 파트너',period:'기간 미설정',eye:'공식 연간 성과 보고서',title:'제공 가능한 ESG 성과 요약',lead:'내용 완성도, RCSCA 확인 및 출처 증빙 체계 검사를 통과한 성과만 포함합니다. 이는 협력 성과 기록이며 제3자 ESG 인증이나 보증이 아닙니다.',items:'건 제공 가능한 성과',sdg:'SDG 연결: ',evidence:'확인 근거: ',source:'출처: ',verified:'확인된 출처',print:'연간 성과 보고서 인쇄／저장',note:'이 보고서는 RCSCA 플랫폼이 확인된 협력 기록을 바탕으로 정리하며 기업 내부 관리 및 지속가능경영 보고 자료에 사용됩니다. 회계, 검증, 인증 또는 제3자 보증 의견을 구성하지 않습니다.'}
};
export default function LiveFormalAnnualReport(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<any[]>([]),[company,setCompany]=useState(c.company);useEffect(()=>{setCompany(c.company);(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const[{data:r},{data:e}]=await Promise.all([s.from('enterprise_esg_delivery_readiness').select('*').eq('enterprise_id',eu.enterprise_id).eq('delivery_ready',true),s.from('enterprises').select('display_name,legal_name').eq('id',eu.enterprise_id).maybeSingle()]);setRows(r||[]);if(e?.display_name||e?.legal_name)setCompany(e.display_name||e.legal_name)})()},[locale]);const periods=useMemo(()=>Array.from(new Set(rows.map(r=>r.period_label||c.period))),[rows,locale]);if(!rows.length)return null;return <section className="esgAnnualPanel formalReport"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{company}｜{c.title}</h2></div><p>{c.lead}</p></div>{periods.map(p=>{const items=rows.filter(r=>(r.period_label||c.period)===p);const sdgs=Array.from(new Set(items.flatMap(r=>r.sdg_tags||[])));return <article className="privacyCallout" key={p}><strong>{p}｜{items.length} {c.items}</strong>{sdgs.length?<p>{c.sdg}{sdgs.join(' · ')}</p>:null}{items.map(r=><div key={r.id} className="reportOutcome"><h3>{r.title}</h3><p>{r.summary}</p>{r.metric_label&&r.metric_value!=null?<p><b>{r.metric_label}：</b>{r.metric_value} {r.metric_unit||''}</p>:null}<p>{c.evidence}{r.evidence_note||'—'}｜{c.source}{r.source_reference||c.verified}</p></div>)}</article>})}<button className="esgLead" onClick={()=>window.print()}>{c.print}</button><p className="evidenceNote">{c.note}</p></section>}
