'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'成果證據鏈',title:'每一筆成果，都能回到它真正發生的地方。',lead:'報告素材不是單獨存在的漂亮文字；系統保留案件、媒合或公益核實來源，方便企業內部稽核與年度報告查證。',pending:'來源待整理',verified:'來源已核實',unverified:'來源尚未完成核實',evidence:'核實依據：'},
 en:{eye:'Outcome evidence chain',title:'Every outcome can be traced back to where it actually happened.',lead:'Reporting assets are not isolated polished text. Case, matching, and verified participation sources are retained for internal audit and annual-report verification.',pending:'Source pending',verified:'Source verified',unverified:'Source verification incomplete',evidence:'Verification basis: '},
 ja:{eye:'成果の証拠チェーン',title:'すべての成果を、実際に起きた場所までたどれます。',lead:'報告素材は単独のきれいな文章ではありません。案件、マッチング、公益参加の確認元を保持し、社内監査や年次報告の確認に利用できます。',pending:'出典を整理中',verified:'出典確認済み',unverified:'出典確認が未完了',evidence:'確認根拠：'},
 ko:{eye:'성과 증빙 체계',title:'모든 성과는 실제로 발생한 곳까지 추적할 수 있습니다.',lead:'보고 자료는 독립된 문구가 아닙니다. 사례, 매칭 또는 공익 참여 확인 출처를 보관해 내부 감사와 연간 보고서 검증에 활용합니다.',pending:'출처 정리 중',verified:'출처 확인 완료',unverified:'출처 확인 미완료',evidence:'확인 근거: '}
};
export default function LiveEvidenceChain(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<any[]>([]);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const{data}=await s.from('enterprise_esg_evidence_chain').select('*').eq('enterprise_id',eu.enterprise_id).eq('report_ready',true);setRows(data||[])})()},[locale]);if(!rows.length)return null;return <section className="esgAnnualPanel"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{c.title}</h2></div><p>{c.lead}</p></div>{rows.map(r=><article className="privacyCallout" key={r.asset_id}><strong>{r.title}</strong><p>{r.source_reference||c.pending} · {r.source_verified?c.verified:c.unverified}</p>{r.evidence_note&&<p>{c.evidence}{r.evidence_note}</p>}</article>)}</section>}
