'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Row={id:string;title:string;period_label:string|null;quality_issues:string[]|null;source_verified:boolean;delivery_ready:boolean};
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'交付前檢查',title:'不是整理完，就代表可以交付。',lead:'正式成果需同時通過內容完整、核實依據、來源證據與報告使用狀態檢查。',current:'目前成果',ready:'筆可正式交付',note:'未通過的項目會保留原因，不會被包裝成完成成果。',period:'未設定期間',verified:'來源已核實',unverified:'來源證據尚未完成',todo:'待補：',separator:'、'},
 en:{eye:'Pre-delivery check',title:'Organized does not automatically mean deliverable.',lead:'Formal outcomes must pass completeness, verification basis, source evidence, and reporting-use checks.',current:'Current outcomes',ready:'ready for formal delivery',note:'Items that do not pass retain their reasons and are never presented as completed outcomes.',period:'Period not set',verified:'Source verified',unverified:'Source evidence incomplete',todo:'To complete: ',separator:', '},
 ja:{eye:'納品前チェック',title:'整理済みでも、そのまま納品できるとは限りません。',lead:'正式な成果は、内容の完全性、確認根拠、出典証拠、報告利用状態のすべてを確認します。',current:'現在の成果',ready:'件が正式納品可能',note:'未通過項目は理由を保持し、完了成果として見せることはありません。',period:'期間未設定',verified:'出典確認済み',unverified:'出典証拠が未完了',todo:'要追加：',separator:'、'},
 ko:{eye:'제공 전 점검',title:'정리가 끝났다고 바로 제공할 수 있는 것은 아닙니다.',lead:'공식 성과는 내용 완성도, 확인 근거, 출처 증빙 및 보고서 사용 상태를 모두 통과해야 합니다.',current:'현재 성과',ready:'건 공식 제공 가능',note:'통과하지 못한 항목은 이유를 남기며 완료된 성과로 포장하지 않습니다.',period:'기간 미설정',verified:'출처 확인 완료',unverified:'출처 증빙 미완료',todo:'보완 필요: ',separator:', '}
};
export default function LiveDeliveryReadiness(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const{data}=await s.from('enterprise_esg_delivery_readiness').select('id,title,period_label,quality_issues,source_verified,delivery_ready').eq('enterprise_id',eu.enterprise_id);setRows((data||[]) as Row[])})()},[locale]);if(!rows.length)return null;const ready=rows.filter(x=>x.delivery_ready).length;return <section className="esgAssetPanel"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{c.title}</h2></div><p>{c.lead}</p></div><div className="assetGrid"><article><small>{c.current}</small><h3>{ready} / {rows.length} {c.ready}</h3><p>{c.note}</p></article>{rows.filter(x=>!x.delivery_ready).slice(0,5).map(x=><article key={x.id}><small>{x.period_label||c.period}</small><h3>{x.title}</h3><p>{x.source_verified?c.verified:c.unverified}</p>{x.quality_issues?.length?<p className="evidenceNote">{c.todo}{x.quality_issues.join(c.separator)}</p>:null}</article>)}</div></section>}
