'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Row={period_label:string;report_ready_assets:number;asset_types:number;sdg_tags:string[];items:any[]};
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'年度成果報告',title:'企業可以直接帶走的成果結構。',lead:'每一筆都保留成果敘述、量化指標、核實依據與來源，可再整理進永續報告、官網或內部簡報。',available:'筆可用成果',types:'類',evidence:'核實依據：',pending:'待補充'},
 en:{eye:'Annual Outcome Report',title:'A usable outcome structure organizations can take forward.',lead:'Each item retains its narrative, metric, verification basis, and source for sustainability reports, websites, or internal presentations.',available:'report-ready outcomes',types:'categories',evidence:'Verification basis: ',pending:'Pending'},
 ja:{eye:'年間成果報告',title:'企業がそのまま活用できる成果構造。',lead:'各項目に成果説明、定量指標、確認根拠、出典を保持し、サステナビリティ報告、Webサイト、社内資料に整理できます。',available:'件の利用可能な成果',types:'種類',evidence:'確認根拠：',pending:'要追加'},
 ko:{eye:'연간 성과 보고서',title:'기업이 바로 활용할 수 있는 성과 구조입니다.',lead:'각 항목에 성과 설명, 정량 지표, 확인 근거와 출처를 보관해 지속가능경영 보고서, 웹사이트 또는 내부 발표 자료로 정리할 수 있습니다.',available:'건 사용 가능한 성과',types:'개 유형',evidence:'확인 근거: ',pending:'보완 필요'}
};
export default function LiveAnnualReport(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const{data}=await s.from('enterprise_annual_report').select('*').eq('enterprise_id',eu.enterprise_id);setRows((data||[]) as Row[])})()},[locale]);if(!rows.length)return null;return <section className="esgAnnualPanel"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{c.title}</h2></div><p>{c.lead}</p></div>{rows.map(r=><article className="card" key={r.period_label}><small>{r.period_label}</small><h3>{r.report_ready_assets} {c.available} · {r.asset_types} {c.types}</h3>{r.sdg_tags?.length>0&&<p className="esgTags">{r.sdg_tags.join(' · ')}</p>}<div>{(r.items||[]).map((x:any)=><div key={x.id} className="privacyCallout"><strong>{x.title}</strong><p>{x.summary}</p>{x.metric_label&&x.metric_value!==null&&<p>{x.metric_label}：{x.metric_value}{x.metric_unit||''}</p>}<p>{c.evidence}{x.evidence_note||c.pending}</p></div>)}</div></article>)}</section>}
