'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Row={period_label:string;report_ready_assets:number;asset_categories:number;metric_value_total:number|string;sdg_tags:string[]|null};
const copy:Record<Locale,any>={
 'zh-Hant':{eye:'年度 ESG 摘要',title:'把核實成果整理成年度報告索引。',lead:'只計入已核准且標記為可供報告使用的素材；不同單位的量化數值不應混加解讀，因此總值僅作資料完整性提示。',available:'筆可用成果',types:'種成果類型',noSdg:'尚未設定 SDG 對應'},
 en:{eye:'Annual ESG Summary',title:'Organize verified outcomes into an annual reporting index.',lead:'Only approved assets marked for reporting are included. Quantitative values with different units must not be combined, so totals indicate data completeness only.',available:'report-ready outcomes',types:'outcome categories',noSdg:'No SDG mapping set'},
 ja:{eye:'年間ESGサマリー',title:'確認済み成果を年間報告の索引に整理します。',lead:'承認済みかつ報告利用可とされた素材だけを集計します。異なる単位の数値は合算解釈せず、合計値はデータ完全性の目安に限ります。',available:'件の利用可能な成果',types:'種類の成果',noSdg:'SDG対応は未設定'},
 ko:{eye:'연간 ESG 요약',title:'확인된 성과를 연간 보고서 색인으로 정리합니다.',lead:'승인되고 보고서 사용 가능으로 표시된 자료만 포함합니다. 단위가 다른 수치는 합산 해석하지 않으며 총값은 데이터 완성도 확인에만 사용합니다.',available:'건 사용 가능한 성과',types:'개 성과 유형',noSdg:'SDG 연결 미설정'}
};
export default function LiveAnnualESGSummary(){const{locale}=useI18n();const c=copy[locale];const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const{data:eu}=await s.from('enterprise_users').select('enterprise_id').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu?.enterprise_id)return;const{data}=await s.from('enterprise_esg_annual_summary').select('period_label,report_ready_assets,asset_categories,metric_value_total,sdg_tags').eq('enterprise_id',eu.enterprise_id);setRows((data||[]) as Row[])})()},[locale]);if(!rows.length)return null;return <section className="esgAnnualPanel"><div className="sectionHead"><div><div className="eyebrow">{c.eye}</div><h2>{c.title}</h2></div><p>{c.lead}</p></div><div className="assetGrid">{rows.map(r=><article key={r.period_label}><small>{r.period_label}</small><h3>{r.report_ready_assets} {c.available}</h3><p>{r.asset_categories} {c.types}</p>{r.sdg_tags?.length?<p className="esgTags">{r.sdg_tags.join(' · ')}</p>:<p>{c.noSdg}</p>}</article>)}</div></section>}
