'use client'
import {useEffect,useState} from 'react'
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser'
const labels:any={submitted:'已送出',under_review:'評估中',needs_info:'待補資料',approved:'已確認',matched:'執行中',completed:'已完成',rejected:'未承接',cancelled:'已取消'}
const eventLabels:any={created:'建立案件',status_changed:'進度更新',assigned:'承辦更新',note:'RCSCA 回覆',enterprise_reply:'企業補件／回覆',completed:'案件完成'}
export default function LiveServiceRequests(){
 const [rows,setRows]=useState<any[]>([]);const [events,setEvents]=useState<Record<string,any[]>>({});const [reply,setReply]=useState<Record<string,string>>({});const [msg,setMsg]=useState('')
 async function load(){const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session)return;const {data}=await s.from('enterprise_service_requests').select('*').eq('requester_user_id',session.user.id).order('created_at',{ascending:false});const list=data||[];setRows(list);if(list.length){const ids=list.map((x:any)=>x.id);const {data:ev}=await s.from('enterprise_service_request_events').select('*').in('request_id',ids).order('created_at',{ascending:true});const grouped:Record<string,any[]>={};(ev||[]).forEach((e:any)=>{(grouped[e.request_id] ||= []).push(e)});setEvents(grouped)}}
 useEffect(()=>{load()},[])
 async function send(id:string){const text=(reply[id]||'').trim();if(!text)return;const s=getSupabaseBrowserClient();const {error}=await s.rpc('enterprise_reply_service_request',{p_request_id:id,p_message:text});setMsg(error?'送出失敗，請稍後再試。':'已送出補件／回覆。');if(!error){setReply(v=>({...v,[id]:''}));load()}}
 if(!rows.length)return <p className="formNote">目前沒有正式 ESG 合作案件。</p>;
 return <div>{msg&&<p className="formNote">{msg}</p>}<div className="stateList">{rows.map(r=><article key={r.id} className="caseCard"><div className="stateMeta"><small>{r.service_tier==='annual'?'年度 ESG 合作':r.service_tier==='project'?'專案執行':'合作健檢'}</small><span>{r.case_number}</span></div><h3>{r.company_name}</h3><div className="stateRow"><span className={`statusChip status-${r.status}`}>{labels[r.status]||r.status}</span><span>{new Date(r.updated_at).toLocaleDateString('zh-TW')}</span></div><p>{r.goal||'尚未填寫合作目標'}</p>{r.admin_note&&<p><strong>RCSCA 回覆：</strong>{r.admin_note}</p>}{r.next_action&&<p><strong>下一步：</strong>{r.next_action}{r.next_action_due_at?` · ${new Date(r.next_action_due_at).toLocaleDateString('zh-TW')}`:''}</p>}<div className="caseTimeline"><h4>案件時間軸</h4>{(events[r.id]||[]).length?(events[r.id]||[]).map((e:any)=><div className="timelineItem" key={e.id}><span>{new Date(e.created_at).toLocaleDateString('zh-TW')}</span><div><strong>{eventLabels[e.event_type]||'案件更新'}</strong>{e.note&&<p>{e.note}</p>}</div></div>):<p className="formNote">案件歷程會隨處理進度逐步建立。</p>}</div>{!['completed','rejected','cancelled'].includes(r.status)&&<div className="caseReply"><textarea placeholder="補充資料、回覆 RCSCA 或說明目前狀況" value={reply[r.id]||''} onChange={e=>setReply(v=>({...v,[r.id]:e.target.value}))}/><button onClick={()=>send(r.id)}>送出補件／回覆</button></div>}</article>)}</div></div>}
