-- Canonical export recovered read-only from Staging migration history.
-- Version: 20260831070832; name: enterprise_case_management

alter table public.enterprise_service_requests add column if not exists assigned_to uuid references public.profiles(id), add column if not exists assigned_at timestamptz, add column if not exists next_action text, add column if not exists next_action_due_at timestamptz, add column if not exists completed_at timestamptz;
create table if not exists public.enterprise_service_request_events (id uuid primary key default gen_random_uuid(),request_id uuid not null references public.enterprise_service_requests(id) on delete cascade,event_type text not null,status public.review_status,note text,visible_to_enterprise boolean not null default true,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
alter table public.enterprise_service_request_events enable row level security;
create policy "enterprise case events own read" on public.enterprise_service_request_events for select to authenticated using (exists(select 1 from public.enterprise_service_requests r where r.id=request_id and (r.requester_user_id=(select auth.uid()) or (r.enterprise_id is not null and private.is_enterprise_user(r.enterprise_id)))) and visible_to_enterprise=true);
create policy "enterprise case events admin read" on public.enterprise_service_request_events for select to authenticated using (private.is_admin(null));
create index if not exists idx_enterprise_service_requests_status_assignee on public.enterprise_service_requests(status,assigned_to,created_at desc);
create index if not exists idx_enterprise_service_request_events_request_created on public.enterprise_service_request_events(request_id,created_at desc);
create or replace function public.admin_update_enterprise_service_request(p_request_id uuid,p_status text,p_assigned_to uuid default null,p_note text default null,p_next_action text default null,p_next_action_due_at timestamptz default null,p_visible_to_enterprise boolean default true) returns void language plpgsql security definer set search_path=public as $$ declare v_actor uuid:=auth.uid(); v_old_status text; v_requester uuid; begin if v_actor is null or not exists(select 1 from public.admin_roles where user_id=v_actor and role_key in ('super_admin','admin','enterprise_reviewer','case_manager')) then raise exception 'insufficient_privilege'; end if; if p_status not in ('submitted','under_review','needs_info','approved','matched','completed','rejected','cancelled') then raise exception 'invalid_status'; end if; select status::text,requester_user_id into v_old_status,v_requester from public.enterprise_service_requests where id=p_request_id for update; if not found then raise exception 'request_not_found'; end if; update public.enterprise_service_requests set status=p_status::public.review_status,assigned_to=coalesce(p_assigned_to,assigned_to),assigned_at=case when p_assigned_to is not null and assigned_to is distinct from p_assigned_to then now() else assigned_at end,admin_note=coalesce(p_note,admin_note),next_action=p_next_action,next_action_due_at=p_next_action_due_at,completed_at=case when p_status='completed' then coalesce(completed_at,now()) else completed_at end,updated_at=now() where id=p_request_id; insert into public.enterprise_service_request_events(request_id,event_type,status,note,visible_to_enterprise,created_by) values(p_request_id,case when v_old_status=p_status then 'update' else 'status_change' end,p_status::public.review_status,p_note,p_visible_to_enterprise,v_actor); insert into public.audit_logs(actor_user_id,actor_role,action,subject_type,subject_id,note) values(v_actor,'enterprise_case_manager','enterprise_service_request_'||p_status,'enterprise_service_request',p_request_id::text,p_note); if v_requester is not null and v_old_status<>p_status then insert into public.user_notifications(recipient_user_id,kind,title,body,related_type,related_id) select v_requester,'enterprise_case_update','企業 ESG 合作案件進度更新','案件狀態已更新，可至企業合作進度查看。','enterprise_service_request',p_request_id where not exists(select 1 from public.user_notifications n where n.recipient_user_id=v_requester and n.related_type='enterprise_service_request' and n.related_id=p_request_id and n.kind='enterprise_case_update' and n.created_at>now()-interval '5 minutes'); end if; if p_status='completed' then perform public.queue_completed_outcome('enterprise_service_request',p_request_id,(select enterprise_id from public.enterprise_service_requests where id=p_request_id),true,true); end if; end; $$;
revoke all on function public.admin_update_enterprise_service_request(uuid,text,uuid,text,text,timestamptz,boolean) from public,anon; grant execute on function public.admin_update_enterprise_service_request(uuid,text,uuid,text,text,timestamptz,boolean) to authenticated;
