-- Canonical export recovered read-only from Staging migration history.
-- Version: 20260831162352; name: v430_network_profiles_rewards_reconcile_v2

create table if not exists public.network_profiles (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,enterprise_id uuid references public.enterprises(id) on delete set null,owner_type text not null default 'person' check(owner_type in ('person','enterprise')),category text not null,display_name text not null,region text,website_url text,public_description text,public_visible boolean not null default true,status public.review_status not null default 'submitted',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,category));
create table if not exists public.my_one_preferences (user_id uuid primary key references public.profiles(id) on delete cascade,share_modes text[] not null default '{}',updated_at timestamptz not null default now(),created_at timestamptz not null default now());
alter table public.network_profiles enable row level security; alter table public.my_one_preferences enable row level security;
grant select,insert,update on public.network_profiles to authenticated; grant select,insert,update on public.my_one_preferences to authenticated; grant select on public.network_profiles to anon;
drop policy if exists "network profiles public approved read" on public.network_profiles; create policy "network profiles public approved read" on public.network_profiles for select using ((public_visible=true and status='approved'::public.review_status) or user_id=(select auth.uid()) or private.is_admin(null));
drop policy if exists "network profiles own insert" on public.network_profiles; create policy "network profiles own insert" on public.network_profiles for insert to authenticated with check (user_id=(select auth.uid()) and status='submitted'::public.review_status);
drop policy if exists "network profiles own update before approval" on public.network_profiles; create policy "network profiles own update before approval" on public.network_profiles for update to authenticated using (user_id=(select auth.uid()) and status in ('draft','submitted','needs_info','rejected','cancelled')) with check (user_id=(select auth.uid()) and status in ('submitted','needs_info','cancelled'));
drop policy if exists "my one preferences self read" on public.my_one_preferences; create policy "my one preferences self read" on public.my_one_preferences for select to authenticated using (user_id=(select auth.uid()) or private.is_admin(null));
drop policy if exists "my one preferences self insert" on public.my_one_preferences; create policy "my one preferences self insert" on public.my_one_preferences for insert to authenticated with check (user_id=(select auth.uid()));
drop policy if exists "my one preferences self update" on public.my_one_preferences; create policy "my one preferences self update" on public.my_one_preferences for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create index if not exists idx_network_profiles_public_category_region on public.network_profiles(category,region,status) where public_visible=true; create index if not exists idx_network_profiles_user_status on public.network_profiles(user_id,status,updated_at desc);
create table if not exists public.reward_catalog (id uuid primary key default gen_random_uuid(),enterprise_id uuid references public.enterprises(id) on delete set null,category text not null check(category in ('daily','selected','rare','secret')),title text not null,description text,point_cost integer not null default 0 check(point_cost>=0),stock_total integer,stock_remaining integer,min_level integer check(min_level between 1 and 5),min_footprints integer not null default 0,status public.review_status not null default 'draft',starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.reward_redemptions (id uuid primary key default gen_random_uuid(),reward_id uuid not null references public.reward_catalog(id) on delete restrict,user_id uuid not null references public.profiles(id) on delete cascade,point_cost integer not null check(point_cost>=0),status public.review_status not null default 'submitted',redemption_code text unique,expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.reward_catalog enable row level security; alter table public.reward_redemptions enable row level security; grant select on public.reward_catalog to anon,authenticated; grant select,insert on public.reward_redemptions to authenticated;
drop policy if exists "approved rewards public read" on public.reward_catalog; create policy "approved rewards public read" on public.reward_catalog for select using (status='approved'::public.review_status or private.is_admin(null));
drop policy if exists "redemptions self read" on public.reward_redemptions; create policy "redemptions self read" on public.reward_redemptions for select to authenticated using (user_id=(select auth.uid()) or private.is_admin(null));
drop policy if exists "redemptions self request" on public.reward_redemptions; create policy "redemptions self request" on public.reward_redemptions for insert to authenticated with check (user_id=(select auth.uid()) and status='submitted'::public.review_status);
create index if not exists idx_reward_catalog_status_category on public.reward_catalog(status,category); create index if not exists idx_reward_redemptions_user_created on public.reward_redemptions(user_id,created_at desc);
