import SiteHeader from '../SiteHeader';
const One=()=> <span className="oneMark"><b>1</b><i>%</i></span>;
export default function Cycle(){return <main className="cyclePage">
<SiteHeader/>
<section className="cycleHero"><div className="portalWrap"><div className="eyebrow">善循環核心</div><h1>不是叫更多人來做好事， 而是讓不同的人都有位置進入循環。</h1><p>RCSCA 不把人分成永遠的給予者與接受者。個人、企業、需要、專業與資源，在不同時間扮演不同角色。</p></div></section>
<section className="cycleQuadrant"><div className="portalWrap"><div className="cycleCross"><div className="axis people">個人</div><div className="axis partners">企業</div><div className="axis care">關懷</div><div className="axis connect">連結</div><div className="cycleCoreBig"><span>RCSCA</span><b>Cycle of Goodness</b><One/></div><article className="q q1"><small>個人 × 關懷</small><h3>個人參與關懷</h3><p>公益行動、陪伴、需求協助。</p></article><article className="q q2"><small>企業 × 關懷</small><h3>企業支持需求</h3><p>資源、服務、專業、工作與合作。</p></article><article className="q q3"><small>個人 × 連結</small><h3>個人連結資源</h3><p>專業、人脈、分享、工作與 人脈連結。</p></article><article className="q q4"><small>企業 × 連結</small><h3>企業連結網絡</h3><p>人才、店家、服務、產業與 共享網絡。</p></article></div></div></section>
<section className="portalSection darkPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">善循環如何發生</div><h2>有人分享，有人被連結，角色再改變。</h2></div></div><div className="cycleFlow"><div><b>01</b><strong>分享自己的 1%</strong></div><i>→</i><div><b>02</b><strong>需求與資源被連上</strong></div><i>→</i><div><b>03</b><strong>有人在需要時被接住</strong></div><i>→</i><div><b>04</b><strong>角色開始改變</strong></div><i>→</i><div><b>05</b><strong>新的 1% 再次出現</strong></div></div><blockquote>當一個人的 1%，成為下一個人的開始，善循環就發生了。</blockquote></div></section>
<section className="portalSection cycleCases"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">善循環不是口號</div><h2>同一個 1%，可以在不同角色之間繼續流動。</h2></div><p>以下是機制示意，不把受助者故事當成宣傳商品；正式上線後以可公開、已取得同意的真實案例取代。</p></div><div className="cycleCaseGrid"><article><small>工作機會 × 重新站穩</small><h3>企業提供的，不一定是捐款。</h3><p>企業釋出工作機會 → RCSCA 協助連結合適的人 → 生活逐步穩定 → 未來他也可能用自己的專業回到網絡。</p></article><article><small>專業 × 公益需求</small><h3>一項專業，也能進入關懷。</h3><p>會員提供專業 → 補上公益行動中的實際缺口 → 減少資源浪費 → 下一次需求再由新的節點接續。</p></article><article><small>被接住 × 新的 1%</small><h3>接受，不是永久身份。</h3><p>人在需要時接受支持 → 有能力後選擇自己的方式分享 → 不要求等值、不要求回報原本的提供者。</p></article></div></div></section><section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">角色不是固定的</div><h2>今天分享的人，明天也可能需要被接住。</h2></div><p>接受不代表虧欠；回到善循環 也不要求等值。有人未來回饋的是專業，有人是一份工作，有人只是一個 人脈連結。</p></div></div></section>
<section className="cycleCaseCta"><div className="portalWrap"><div><small>善循環不是口號</small><h2>看三個機制案例，理解角色怎麼真的開始流動。</h2></div><a href="/cycle-of-goodness/cases">查看善循環案例 →</a></div></section></main>}
