import LanguageSwitcher from '../LanguageSwitcher';
const One=()=> <span className="oneMark"><b>1</b><i>%</i></span>;
export default function Cycle(){return <main className="cyclePage">
<header className="nav"><div className="navInner"><a className="brandLockup" href="/"><span className="brandStack"><span className="brandRcsca">RCSCA</span><small>Cycle of Goodness</small></span><span className="brandCross">×</span><One/></a><nav><a href="/my-1percent">MY 1%</a><a href="/1percent-partner">1% PARTNER</a><a href="/care-actions">公益行動</a><a href="/1percent-network">1% NETWORK</a><a className="navActive" href="/cycle-of-goodness">CYCLE OF GOODNESS</a><LanguageSwitcher/></nav></div></header>
<section className="cycleHero"><div className="portalWrap"><div className="eyebrow">THE CORE SYSTEM</div><h1>不是叫更多人來做好事， 而是讓不同的人都有位置進入循環。</h1><p>RCSCA 不把人分成永遠的給予者與接受者。個人、企業、需要、專業與資源，在不同時間扮演不同角色。</p></div></section>
<section className="cycleQuadrant"><div className="portalWrap"><div className="cycleCross"><div className="axis people">PEOPLE</div><div className="axis partners">PARTNERS</div><div className="axis care">CARE</div><div className="axis connect">CONNECT</div><div className="cycleCoreBig"><span>RCSCA</span><b>Cycle of Goodness</b><One/></div><article className="q q1"><small>PEOPLE × CARE</small><h3>個人參與關懷</h3><p>公益行動、陪伴、需求協助。</p></article><article className="q q2"><small>PARTNERS × CARE</small><h3>企業支持需求</h3><p>資源、服務、專業、工作與合作。</p></article><article className="q q3"><small>PEOPLE × CONNECT</small><h3>個人連結資源</h3><p>專業、人脈、分享、工作與 Connection。</p></article><article className="q q4"><small>PARTNERS × CONNECT</small><h3>企業連結網絡</h3><p>人才、店家、服務、產業與 Network。</p></article></div></div></section>
<section className="portalSection darkPortal"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">HOW THE CYCLE HAPPENS</div><h2>有人分享，有人被連結，角色再改變。</h2></div></div><div className="cycleFlow"><div><b>01</b><strong>分享自己的 1%</strong></div><i>→</i><div><b>02</b><strong>需求與資源被連上</strong></div><i>→</i><div><b>03</b><strong>有人在需要時被接住</strong></div><i>→</i><div><b>04</b><strong>角色開始改變</strong></div><i>→</i><div><b>05</b><strong>新的 1% 再次出現</strong></div></div><blockquote>當一個人的 1%，成為下一個人的開始，Cycle of Goodness 就發生了。</blockquote></div></section>
<section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">NO FIXED ROLES</div><h2>今天分享的人，明天也可能需要被接住。</h2></div><p>接受不代表虧欠；回到 Cycle 也不要求等值。有人未來回饋的是專業，有人是一份工作，有人只是一個 Connection。</p></div></div></section>
</main>}
