'use client';
import {useEffect,useState} from 'react';import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';import {Locale,useI18n} from '../../i18n';
type Row={kind:string;id:string;title:string;status:string;updated_at:string;summary:string|null;href:string};
const copy:Record<Locale,any>={
 'zh-Hant':{network:'共享媒合',support:'關懷需求',enterprise:'企業 ESG 案件',partial:'部分進度暫時無法讀取，但不影響其他已載入紀錄。',loading:'正在讀取需求進度…',signin:'請先登入',signinLead:'登入後只會看到自己的需求、媒合與合作案件進度。',login:'前往登入 →',empty:'目前沒有進行中的需求。',emptyLead:'需要找專業、提出生活缺口或建立企業合作案件時，都會集中回到這裡追蹤。',request:'提出共享需求 →',updated:'更新 ',view:'查看相關流程 →',labels:{draft:'草稿',submitted:'已送出',under_review:'評估中',needs_info:'需要補充',approved:'已核准',matched:'媒合中',completed:'已完成',rejected:'未通過',cancelled:'已取消'}},
 en:{network:'Sharing match',support:'Care request',enterprise:'Enterprise ESG case',partial:'Some progress could not be loaded. Other available records are unaffected.',loading:'Loading request progress…',signin:'Please sign in',signinLead:'After sign-in, you only see your own requests, matches, and collaboration cases.',login:'Go to sign in →',empty:'No active requests right now.',emptyLead:'Requests for expertise, personal support, or enterprise collaboration will be tracked here.',request:'Submit a sharing request →',updated:'Updated ',view:'View related workflow →',labels:{draft:'Draft',submitted:'Submitted',under_review:'Under review',needs_info:'More information needed',approved:'Approved',matched:'Matching',completed:'Completed',rejected:'Not approved',cancelled:'Cancelled'}},
 ja:{network:'共有マッチング',support:'ケアの依頼',enterprise:'企業ESG案件',partial:'一部の進捗を読み込めませんでした。読み込み済みの記録には影響しません。',loading:'依頼の進捗を読み込み中…',signin:'ログインしてください',signinLead:'ログイン後、本人の依頼、マッチング、連携案件だけを表示します。',login:'ログインへ →',empty:'進行中の依頼はありません。',emptyLead:'専門家探し、生活上の不足、企業連携の依頼はここでまとめて追跡できます。',request:'共有の依頼を提出 →',updated:'更新 ',view:'関連する手続きへ →',labels:{draft:'下書き',submitted:'提出済み',under_review:'審査中',needs_info:'情報の追加が必要',approved:'承認済み',matched:'マッチング中',completed:'完了',rejected:'非承認',cancelled:'キャンセル済み'}},
 ko:{network:'공유 매칭',support:'돌봄 요청',enterprise:'기업 ESG 사례',partial:'일부 진행 상황을 불러오지 못했지만 다른 기록에는 영향을 주지 않습니다.',loading:'요청 진행 상황을 불러오는 중…',signin:'로그인이 필요합니다',signinLead:'로그인 후 본인의 요청, 매칭 및 협력 사례만 표시됩니다.',login:'로그인으로 →',empty:'현재 진행 중인 요청이 없습니다.',emptyLead:'전문가 연결, 생활 지원 또는 기업 협력 요청을 여기에서 통합 추적합니다.',request:'공유 요청 제출 →',updated:'업데이트 ',view:'관련 절차 보기 →',labels:{draft:'초안',submitted:'제출됨',under_review:'검토 중',needs_info:'추가 정보 필요',approved:'승인됨',matched:'매칭 중',completed:'완료',rejected:'승인되지 않음',cancelled:'취소됨'}}
};
const dateLocale:Record<Locale,string>={'zh-Hant':'zh-TW',en:'en-US',ja:'ja-JP',ko:'ko-KR'};
export default function LiveRequests(){
 const{locale}=useI18n();const c=copy[locale];const[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[rows,setRows]=useState<Row[]>([]),[notice,setNotice]=useState('');
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session){setLoading(false);return;}setSignedIn(true);const [network,support,service]=await Promise.all([
  s.from('network_requests').select('id,request_kind,title,status,updated_at,public_summary').eq('requester_user_id',session.user.id).order('updated_at',{ascending:false}),
  s.from('support_cases').select('id,title,status,updated_at,public_summary').eq('owner_user_id',session.user.id).order('updated_at',{ascending:false}),
  s.from('enterprise_service_requests').select('id,case_number,company_name,status,updated_at,next_action').eq('requester_user_id',session.user.id).order('updated_at',{ascending:false})
 ]);const all:Row[]=[];for(const r of network.data||[])all.push({kind:`${c.network} · ${r.request_kind}`,id:r.id,title:r.title,status:r.status,updated_at:r.updated_at,summary:r.public_summary,href:'/1percent-network/matches'});for(const r of support.data||[])all.push({kind:c.support,id:r.id,title:r.title,status:r.status,updated_at:r.updated_at,summary:r.public_summary,href:`/account/requests/support/${r.id}`});for(const r of service.data||[])all.push({kind:c.enterprise,id:r.id,title:`${r.case_number} · ${r.company_name}`,status:r.status,updated_at:r.updated_at,summary:r.next_action,href:'/1percent-partner/requests'});if([network,support,service].some(x=>x.error))setNotice(c.partial);all.sort((a,b)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime());setRows(all);setLoading(false)})()},[locale]);
 if(loading)return <p>{c.loading}</p>;
 if(!signedIn)return <div className="privacyCallout"><strong>{c.signin}</strong><p>{c.signinLead}</p><a href="/login">{c.login}</a></div>;
 return <>{notice&&<div className="workflowNotice">{notice}</div>}{!rows.length?<div className="privacyCallout"><strong>{c.empty}</strong><p>{c.emptyLead}</p><a href="/member-network/request">{c.request}</a></div>:<div className="stateList">{rows.map(r=><article key={`${r.kind}-${r.id}`}><div className="stateMeta"><small>{r.kind}</small><span>{r.id.slice(0,8)}</span></div><h3>{r.title}</h3><div className="stateRow"><span className={`statusChip status-${r.status}`}>{c.labels[r.status]||r.status}</span><span>{c.updated}{new Date(r.updated_at).toLocaleDateString(dateLocale[locale])}</span></div>{r.summary&&<p>{r.summary}</p>}<a className="textRoute" href={r.href}>{c.view}</a></article>)}</div>}</>;
}
