'use client';
import {useEffect,useState} from 'react';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';
type Member={user_id:string;role:string;profiles:{display_name:string|null;email:string|null}|null};
const roleLabel:Record<string,string>={manager:'管理者',editor:'協作者',viewer:'查看者'};
export default function LiveEnterpriseTeam(){
 const [enterpriseId,setEnterpriseId]=useState(''),[myRole,setMyRole]=useState(''),[rows,setRows]=useState<Member[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState('viewer'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session){setMsg('請先登入企業帳號。');return;}const {data:eu}=await s.from('enterprise_users').select('enterprise_id,role').eq('user_id',session.user.id).limit(1).maybeSingle();if(!eu){setMsg('這個帳號尚未連結企業。');return;}setEnterpriseId(eu.enterprise_id);setMyRole(eu.role);const {data,error}=await s.from('enterprise_users').select('user_id,role,profiles(display_name,email)').eq('enterprise_id',eu.enterprise_id).order('created_at');if(error)setMsg('目前無法讀取企業成員。');else setRows((data||[]) as any)}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');const s=getSupabaseBrowserClient();const {error}=await s.rpc('enterprise_add_member_by_email',{p_enterprise_id:enterpriseId,p_email:email,p_role:role});setBusy(false);if(error){setMsg(error.message.includes('registered_account_not_found')?'找不到這個已註冊帳號；對方需先建立 RCSCA 帳號。':error.message.includes('manager_required')?'只有企業管理者可以調整團隊。':'目前無法更新企業成員。');return;}setEmail('');setMsg('企業成員權限已更新。');load()}
 async function remove(id:string){if(!confirm('確定移除這位企業成員？'))return;const s=getSupabaseBrowserClient();const {error}=await s.rpc('enterprise_remove_member',{p_enterprise_id:enterpriseId,p_user_id:id});setMsg(error?(error.message.includes('last_manager')?'至少必須保留一位企業管理者。':'目前無法移除。'):'已移除企業成員。');if(!error)load()}
 return <section className="portalSection"><div className="portalWrap"><div className="sectionHead"><div><div className="eyebrow">企業帳號與權限</div><h2>同一間企業，可以有多人協作，但權限要清楚。</h2></div><p>管理者可新增成員與調整角色；協作者可處理日常企業內容；查看者只讀取企業內部狀態。</p></div>{msg&&<div className="workflowNotice">{msg}</div>}<div className="partnerReviewList">{rows.map(m=><article key={m.user_id}><div className="partnerReviewMain"><small>{roleLabel[m.role]||m.role}</small><h3>{m.profiles?.display_name||m.profiles?.email||'企業成員'}</h3><p>{m.profiles?.email||'未提供 Email'}</p></div>{myRole==='manager'&&<div className="reviewActions"><button className="dangerAction" onClick={()=>remove(m.user_id)}>移除</button></div>}</article>)}</div>{myRole==='manager'&&<form className="shareCorrection" onSubmit={add}><h3>新增／更新企業成員</h3><input type="email" required placeholder="對方已註冊的 Email" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="viewer">查看者</option><option value="editor">協作者</option><option value="manager">管理者</option></select><button disabled={busy}>{busy?'處理中…':'更新企業成員'}</button><p className="microNote">目前只允許加入已經註冊 RCSCA 的帳號；不透過這裡寄送陌生邀請或建立帳號。</p></form>}</div></section>
}
